from pathlib import Path
import json,re,math,shutil,hashlib
P=Path(__file__).resolve().parents[1]; ROOT=P.parents[3]; OUT=ROOT/'tiles/aaron-video-gen/remotion/src/projects/astra-real-work'; PUB=ROOT/'tiles/aaron-video-gen/remotion/public/astra-real-work'
m=json.loads((P/'audio-generation-manifest.json').read_text()); segments=m['timeline']['segments']; words=m['timeline']['wordTimings']; scenes=[]; shift=3.; duration=math.ceil((m['qa']['durationSeconds']+shift+5)*30)/30
clean=lambda s:re.sub('[^a-z0-9]','',s.lower())
def at(idx,phrase):
 seg=segments[idx]; target=[clean(x) for x in phrase.split()]; pool=[w for w in words if seg['start']-.001<=w['start']<seg['end']]
 vals=[clean(w['word']) for w in pool]
 for k in range(len(vals)-len(target)+1):
  if vals[k:k+len(target)]==target:return pool[k]['start']
 raise ValueError((idx,phrase))
def add(a,b,kind,title,sub='',nodes=None,media=None,facts=None,sources=None,rail=None,tension=False):
 scenes.append({'id':f's{len(scenes):02}','start':round((a+shift)*30)/30,'end':round((b+shift)*30)/30,'kind':kind,'title':title,'sub':sub,'nodes':nodes or [],'media':media,'facts':facts or [],'sources':sources or [],'rail':rail or ('EDITORIAL ILLUSTRATION' if media else 'AARON’S NOTES · REAL WORK'),'tension':tension})
def split(idx,cuts,items):
 bounds=[segments[idx]['start']]+[at(idx,c) for c in cuts]+[segments[idx]['end']]
 for k,item in enumerate(items):add(bounds[k],bounds[k+1],**item)
def s(kind,title,sub='',**kw):return dict(kind=kind,title=title,sub=sub,**kw)
scenes.append({'id':'s00','start':0.,'end':3.,'kind':'cover','title':'ASTRA AT WORK','sub':'GPT-6 in real work · Aaron Guo','nodes':[],'media':'thumbnail.jpg','facts':[],'sources':[],'rail':'EDITORIAL ILLUSTRATION','tension':False})
worker=dict(facts=['worker'],sources=['dev-worker','attachment'],rail='AARON’S DEV EXPERIENCE · ARCHITECTURE ABSTRACTED')
context=dict(facts=['context'],sources=['context'],rail='CODEX DOCUMENTATION · EXPERIMENTAL / OFF BY DEFAULT')
split(0,["I've been using it","That experience"],[s('evidence','The demos are striking.','Official demonstrations',media='blender.png',facts=['demo-exhibits'],sources=['launch'],rail='OPENAI · GPT-6 ASTRA SHOWCASE'),s('flow','My job crossed systems.','Networking. Certificates. Real problems.',nodes=['Azure','Linux','Windows','Database'],**worker),s('statement','More of the job.','That is what I’m willing to delegate.')])
split(1,['Six things stand out'],[s('media','The writing\nfeels more natural.','An everyday workflow, alongside the deployment.',media='writing.png',facts=['smooth']),s('statement','Astra with an actual job.','Inside the tools and systems we already use.')])
split(2,['I wanted a request','Existing connections'],[s('compare','One job. Two environments.','The business requirement comes first.',nodes=['Linux\nBusiness application','Windows\nReporting engine'],**worker),s('flow','From request to returned PDF.','Keep the existing workflow intact.',nodes=['Linux app','Windows service','Database','PDF result'],**worker),s('statement','Fit the existing system.','Connections and workflows still have to work.',**worker)])
split(3,['Astra advanced','But I'],[s('flow','The work around the code.','Azure resources · private networking · existing NAT · SQL trust',nodes=['Azure','Private network','Windows service','SQL certificate'],facts=['worker'],sources=['dev-provision','network-runbook'],rail='AARON’S DEV EXPERIENCE · EXISTING NAT GATEWAY'),s('compare','Autonomy has a scope.','Implementation proceeds inside the agreed boundary.',nodes=['Aaron\nScope and service decisions','Astra\nConfiguration and checks'],**worker),s('media','The pieces\nstay connected.','One task across the working environment.',media='cover.png',**worker)])
split(4,['Later','What impressed'],[s('row','It still met real problems.','The work continued through diagnosis.',nodes=['Network rule rejected','Certificate checks'],tension=True,**worker),s('flow','Follow the failure through.','Read-back and retry checks completed in Dev.',nodes=['PDF generated','Attachment failed','Read back + retry','Dev verified'],**worker),s('statement','Carry the pieces together.','Infrastructure, code, troubleshooting and verification.',**worker)])
split(5,['Another compares'],[s('evidence','2 / Connect the tools.','Blender model · official showcase',media='blender.png',facts=['demo-exhibits'],sources=['launch'],rail='OPENAI · BLENDER MODEL · OFFICIAL DEMONSTRATION'),s('evidence','A result becomes an input.','Google Maps routes · official showcase',media='maps.png',facts=['demo-exhibits'],sources=['launch'],rail='OPENAI · PEDIATRICIAN SEARCH · OFFICIAL DEMONSTRATION')])
split(6,['The useful combination'],[s('row','Ordinary browser work.','Matt Shumer’s firsthand account; tools and access still matter.',nodes=['Newsletters','Inboxes','Advertising'],facts=['browser-work'],sources=['shumer'],rail='MATT SHUMER · ASTRA REVIEW · AUTHOR SELF-REPORT'),s('flow','Keep the handoffs moving.','One less point where the job returns to me.',nodes=['Research','Create','Inspect','Continue'],facts=['whole-job'],sources=['shumer','context'])])
split(7,['Imagine a refactor'],[s('media','3 / Keep the history.','Notes and searchable history. Experimental; off by default.',media='notes.png',**context),s('compare','A refactor, hours later.','A hypothetical example of why earlier context matters.',nodes=['Earlier discovery\nDependency cannot upgrade','Later decision\nKeep the constraint'],**context)])
split(8,['It matters because'],[s('row','Keep the reason, too.','A hypothetical refactor example.',nodes=['Migration failed','Tests showed why','Avoid the same dead end'],**context),s('media','Earlier effort\nstays useful.','Long jobs accumulate discoveries.',media='notes.png',**context)])
split(9,['If I say'],[s('statement','4 / Initiative and direction.','Keep going. Understand a change in scope.'),s('compare','“Keep this in the test environment.”','An illustrative instruction: new direction changes the next steps.',nodes=['Before\nContinue implementation','After\nStay inside Dev'],facts=['skill-review-position'],sources=['guidance'],rail='AARON’S COLLABORATION EXAMPLE')])
split(10,['I would replace','Scope still matters'],[s('row','Review the old skills.','Ambiguous or conflicting instructions can stop useful work.',nodes=['Skills','AGENTS.md','Conflicting rules'],facts=['guidance'],sources=['guidance'],rail='OPENAI · ASTRA USAGE GUIDANCE'),s('compare','Give it a clearer working agreement.','Illustrative wording, not a quotation from the documentation.',nodes=['Old habit\nAsk me after every step','Better agreement\nGoal, checks, decision points'],facts=['skill-review-position'],sources=['guidance']),s('statement','Scope still matters.','Better instructions do not excuse a misunderstood job.',facts=['skill-review-position'],sources=['scope-feedback'],tension=True,rail='DEVELOPER SELF-REPORT · EXTRA INFRASTRUCTURE / EARLY IMPLEMENTATION')])
split(11,["I often begin"],[s('media','5 / More natural prose.','Connected ideas. A more pleasant read.',media='writing.png',facts=['smooth']),s('manuscript','From scattered thoughts to an article.','The writing should carry the thought.',nodes=['Project experience','Half-formed judgment','A coherent article'],facts=['smooth'])])
split(12,['This is my experience'],[s('flow','Let one thought lead to the next.','The next paragraph picks up the question.',nodes=['Experience','Observation','Next question'],facts=['smooth']),s('media','Make the expression\nfit the piece.','Reader, context and tone still contribute.',media='writing.png',facts=['smooth'])])
split(13,['Other users','I would use'],[s('row','6 / Count the whole cost.','One flight-game project. Not a forecast for every user.',nodes=['About 3 hours','45% of weekly allowance'],facts=['game-tools-cost'],sources=['flight-game'],rail='TANIAI_ · GODOT / BLENDER PROJECT · AUTHOR SELF-REPORT'),s('statement','The allowance can run out.','Useful output still has a cost.',facts=['game-tools-cost'],sources=['limits-feedback'],tension=True,rail='INDIVIDUAL USER REPORTS · DIFFERENT TASKS AND SETTINGS'),s('compare','Choose by the job.','Model cost + my time + what gets finished.',nodes=['Small edit\nA lighter model may be enough','Complex work\nConsider the stronger model'])])
split(14,['Greater autonomy','So does the higher price'],[s('media','More trust\nin a longer job.','Across products and systems, within a clear scope.',media='cover.png',facts=['closing-judgment']),s('row','New questions come with autonomy.','How do I verify the result and trace the important decisions?',nodes=['Verify the result','Trace decisions','Audit the work'],facts=['closing-judgment']),s('statement','I’m tempted to buy more room.','The useful work makes me want to use it more.',facts=['closing-judgment'])])
split(15,['AI is still'],[s('media','The excitement\nis still there.','I want the work I watch closely to become work I can trust it with.',media='review.png',facts=['closing-judgment']),s('statement','AI is still surprising me.','I want to feel the next improvement in real work.',facts=['closing-judgment'])])
scenes.append({'id':f's{len(scenes):02}','start':scenes[-1]['end'],'end':duration,'kind':'end','title':'AARON GUO','sub':'AI-NATIVE BUILDER · Human-first thinker','nodes':[],'media':None,'facts':[],'sources':[],'rail':'','tension':False})
# Group exact provider words into phrases. No text rewrite and no extended caption hold.
captions=[];group=[]
for w in words:
 group.append(w)
 if re.search(r'[.!?,;:]$',w['word']) and len(group)>=4 or len(group)>=10:
  captions.append({'start':group[0]['start']+shift,'end':group[-1]['end']+shift,'text':' '.join(x['word'] for x in group)});group=[]
if group: captions.append({'start':group[0]['start']+shift,'end':group[-1]['end']+shift,'text':' '.join(x['word'] for x in group)})
for n,src in {'cover.png':P/'imgs/00-cover-v1.png','thumbnail.jpg':P/'imgs/thumbnail-youtube.jpg','notes.png':P/'imgs/01-retained-notes-v1.png','writing.png':P/'imgs/02-writing-flow-v1.png','review.png':P/'imgs/03-review-lamp-v1.png','blender.png':P/'imgs/evidence/openai-blender.png','maps.png':P/'imgs/evidence/openai-google-maps.png','audio.mp3':P/'audio.mp3','ag-logo.png':ROOT/'assets/aaron-logo-assets/ag-logo.png'}.items():shutil.copy2(src,PUB/n)
for x in scenes:
 d=x['end']-x['start']; x['cues']=[round(v,3) for v in ([.5]+[min(d-.5,3+i*4) for i in range(max(len(x['nodes'])-1,0))])];x['detailCue']=min(1.,d*.2)
data={'duration':duration,'fps':30,'audioOffset':shift,'scenes':scenes,'captions':captions}
OUT.mkdir(parents=True,exist_ok=True);(OUT/'data.ts').write_text('export const filmData = '+json.dumps(data,ensure_ascii=False,indent=2)+';\n');(P/'video-production/timeline.json').write_text(json.dumps(data,ensure_ascii=False,indent=2))
ref={'baseline_id':'ledger-editorial-v1','reference_package':'src/content/blogs/2026-08-19','reference_video':'src/content/blogs/2026-08-19/video-v3.mp4','reference_qa':'src/content/blogs/2026-08-19/video-qa-report.md','inherited_system':'Warm ivory, graphite hierarchy, registered layout geometry, source rails and protected captions; DHH v7 supplies the quiet chaptered music reference.','rejected_legacy_pattern':'Full-frame slide decks, empty title stages, repeating cards, decorative camera motion.','deliberate_deviation':'Astra whole-job illustrations and source screenshots; same restrained editorial grammar. Selected by agent under author request to proceed with current recommended direction.','review_status':'reviewed'}
director={'schema_version':1,'title':'GPT-6 Astra in Real Work','duration_sec':duration,'product_promise':'A real deployment and six observations show what becomes practical to delegate.','style_reference':ref,'visual_budget':{'remotion_motion_target_ratio':.7,'evidence_or_still_target_ratio':.3,'max_generated_video_ratio':0,'max_generated_video_beats':0,'max_semantic_sprite_beats':0},'beats':[]}
board={'schema_version':1,'title':director['title'],'duration_sec':duration,'fps':30,'direction':{'name':'A real job travels across tools','style_family_id':'ledger-editorial-v1','visual_spine':ref['inherited_system'],'motion_density':'balanced','music_strategy':'chaptered','references':[{'id':'ledger','url':'https://youtu.be/5vEEBhbfUWw','borrow':ref['inherited_system'],'avoid':ref['rejected_legacy_pattern']}]},'scenes':[]}
assets={'schema_version':1,'title':director['title'],'duration_sec':duration,'aspect_ratio':'16:9','visual_spine_id':'ledger-editorial-v1','asset_library':{'queries':['calm sparse piano ambient editorial','paper moon'],'selected_asset_ids':['music:b161e820cd4f5741']},'beats':[]}
media_paths={'cover.png':'imgs/00-cover-v1.png','thumbnail.jpg':'imgs/thumbnail-youtube.jpg','notes.png':'imgs/01-retained-notes-v1.png','writing.png':'imgs/02-writing-flow-v1.png','review.png':'imgs/03-review-lamp-v1.png','blender.png':'imgs/evidence/openai-blender.png','maps.png':'imgs/evidence/openai-google-maps.png'}
for x in scenes:
 k=x['kind'];d=x['end']-x['start'];role='evidence' if k=='evidence' else 'emphasis' if k in ['cover','statement','end'] else 'explanation';mode='source-evidence' if k=='evidence' else 'hybrid' if k=='media' else 'generated-still' if k=='cover' else 'motion';template='image-sequence' if k in ['cover','media','evidence'] else 'brand-end-card' if k=='end' else 'editorial-statement' if k=='statement' else 'system-map';intensity='calm' if k in ['cover','media','evidence','statement','end'] else 'structured';recipe='focus-shift' if intensity=='structured' or k=='statement' else 'crossfade' if x['media'] else 'crossfade'
 first_change=.25 if k=='cover' else 0. if k=='end' else 1. if k in ['media','evidence','statement'] else 3. if k=='manuscript' else 2.4 if k=='flow' else .5
 content=[x['title']]+x['nodes']+[x['sub']];content=[v for v in content if v];beats=[{'at_sec':0,'visual':x['title'],'action':'Complete readable scaffold at entry'},{'at_sec':first_change,'visual':x['sub'] or x['title'],'action':'Actual first change: support emphasis, underline, connector or focus, depending on composition'}]
 for t in range(6,max(6,math.ceil(d)-2),6):beats.append({'at_sec':t,'visual':x['nodes'][min(len(x['nodes'])-1,t//6)] if x['nodes'] else x['sub'],'action':'Intentional still hold for the spoken explanation; no additional animation is implied'})
 board['scenes'].append({'id':x['id'],'title':x['title'],'start_sec':x['start'],'end_sec':x['end'],'role':role,'template':template,'intensity':intensity,'purpose':'Make this spoken idea legible: '+x['title'],'entry_mode':'meaningful','entry_visual':x['title'],'first_change_sec':first_change,'motion_recipes':[recipe],'content':content,'beats':beats,'music_cue':'Sparse chaptered music; voice gain fixed at unity. See sound-plan.json.','prototype_required':False,'fallback_template':'image-sequence'})
 director['beats'].append({'id':x['id'],'start_sec':x['start'],'end_sec':x['end'],'narrative_role':'hook' if x['id']=='s00' else 'resolve' if k=='end' else 'evidence' if role=='evidence' else 'challenge' if x['tension'] else 'explain','visual_mode':mode,'intensity':intensity,'entry_mode':'meaningful','entry_visual':x['title'],'first_visual_change_sec':first_change,'visual_reason':'One visual reading job: '+x['title'],'camera_or_motion':recipe+' in a stable registered layout','asset_id':x['id'],'asset_provenance':x['rail'] or 'Owned author brand typography','generated_video_sec':0,'sound_cue':'Chaptered cue only at meaningful turns; constant voice gain.','transition_out':'Clean cut; shared ivory field and caption baseline.','fallback':'Fully readable static composition'})
 assets['beats'].append({'id':x['id'],'start_sec':x['start'],'end_sec':x['end'],'copy':' / '.join(content),'visual_role':role,'asset_type':'source-screenshot' if k=='evidence' else 'generated-still' if x['media'] else 'generated-layout','fact_ids':x['facts'],'source_ids':x['sources'],'asset_path':media_paths.get(x['media'],None),'usage_role':'primary','status':'ready','provenance':x['rail'] or 'Owned native typography','rights':'public-source' if k=='evidence' else 'generated' if x['media'] else 'owned','editorial_approval':'approved' if k=='evidence' else None,'fallback':'Native typography retains the same claim and source boundary.'})
for name,obj in [('director-plan.json',director),('video-storyboard.json',board),('asset-plan.json',assets)]: (P/name).write_text(json.dumps(obj,ensure_ascii=False,indent=2)+'\n')
def fmt(t):
 ms=round(t*1000);return f'{ms//3600000:02}:{ms//60000%60:02}:{ms//1000%60:02},{ms%1000:03}'
(P/'video-captions-en.srt').write_text('\n\n'.join(f'{i+1}\n{fmt(c["start"])} --> {fmt(c["end"])}\n{c["text"]}' for i,c in enumerate(captions))+'\n')
print(f'{len(scenes)} scenes, {len(captions)} exact-text captions, {duration:.3f} seconds.')
