from pathlib import Path
import json,copy
p=Path(__file__).resolve().parent;old=p.parent/'singing-sands-pilot-2026-09-08';d=json.loads((p/'timeline.json').read_text());duration=d['durationFrames']/30
write=lambda name,obj:(p/name).write_text(json.dumps(obj,ensure_ascii=False,indent=2)+'\n')
f=json.loads((old/'fact-pack.json').read_text());f['thesis']='A sensory documentary that follows relative grain motion, synchronization, laboratory avalanches, size selection, and the bounds of competing explanations.'
for id,url,pub,note in [('douady-2006','https://arxiv.org/abs/nlin/0412047','Douady et al. / Physical Review Letters','Relative motion and synchronization theory. Abstract read directly. DOI 10.1103/PhysRevLett.97.018002.'),('dagois-2012','https://agupubs.onlinelibrary.wiley.com/doi/abs/10.1029/2012GL052540','Dagois-Bohy et al. / Geophysical Research Letters','Publisher abstract and laboratory experiment indexed text read. Singing sand on hard-bottom channel; sorted grain comparison. No publisher figures or audio reused.'),('nps-moses','https://npgallery.nps.gov/AssetDetail/ae8d30f9-0da0-42bf-9adb-b2382c85b117','NPS / Kurt Moses','Asset metadata explicitly states Public domain:Full Granting Rights and photographer Kurt Moses; preserve attribution. 1500x998 original downloaded and inspected.')]:f['sources'].append(dict(id=id,url=url,publisher=pub,source_type='primary',verification_status='verified',rights='public-source',notes=note))
for id,claim,src,bound in [('f6','Relative motion of grains during avalanches is linked to dune sound; synchronization is an influential explanation.',['douady-2006'],'Clapping is an original analogy, not an observed microscopic experiment. Motion shown slow, not at audible frequency.'),('f7','Suitable singing-dune sand produced sound in laboratory avalanches in a hard-bottom channel.',['dagois-2012'],'Only under tested conditions; do not claim ordinary sand can always sing.'),('f8','Sorting the mixed-size sand into a narrower grain-size range produced a more defined note.',['dagois-2012'],'Sieve selects existing grains; it does not resize them. No numerical spectrum claimed.'),('f9','Field studies proposed layered-dune waveguides, while other experiments emphasize flowing grains.',['caltech','dagois-2012','douady-2006'],'Competing interpretations; no claim of complete resolution.')]:f['facts'].append(dict(id=id,claim=claim,source_ids=src,confidence='high',usable_in_script=True,sensitivity=bound))
write('fact-pack.json',f)
# Preserve the accepted opening contracts and append the exact new timeline.
for name in ['director-plan.json','asset-plan.json','video-storyboard.json']:
 q=json.loads((old/name).read_text());q['duration_sec']=duration
 key='scenes' if name=='video-storyboard.json' else 'beats';q[key]=[b for b in q[key] if b['start_sec']<49.233 and b['end_sec']<=49.234]
 q[key][-1]['end_sec']=d['introFrames']/30
 if name=='director-plan.json':q['style_reference'].update(baseline_id='sand-documentary-author-approved-pilot',reference_package=str(old.relative_to(Path.cwd())),reference_video=str((old/'pilot.mp4').relative_to(Path.cwd())),reference_qa=str((old/'video-qa-report.md').relative_to(Path.cwd())),deliberate_deviation='User approved pilot voice, motion, pacing, and requested scientific continuation before language polish. Original opening and ending preserved.');q['visual_budget'].update(remotion_motion_target_ratio=.56,evidence_or_still_target_ratio=.44)
 for i,s in enumerate(d['scenes']):
  title=['Relative grain motion','Clapping analogy and synchronized grains','Hard-bottom avalanche channel','Selecting grains with a sieve','Dune-layer hypothesis','Return to the landscape'][i];base=dict(id=s['id'],start_sec=s['start'],end_sec=s['end']);src=[['douady-2006'],['douady-2006'],['dagois-2012'],['dagois-2012'],['caltech','dagois-2012','nps-moses'],['nps-moses','douady-2006']][i];facts=[['f6'],['f6'],['f7'],['f8'],['f9'],['f6','f9']][i]
  if name=='director-plan.json':base.update(narrative_role='explain' if i<5 else 'resolve',visual_mode='motion' if i<5 else 'source-evidence',intensity='structured' if i<5 else 'calm',entry_mode='meaningful',entry_visual=title,first_visual_change_sec=.5,visual_reason='Expose the relationship described by narration, with illustration labels and bounded scientific claims.',camera_or_motion='Deterministic scene clock; relative motion, synchronization, gate lift, grain selection, or a fixed photograph.',asset_id=f'full-{i}',asset_provenance='Original explanatory vector artwork with attributed NPS landscape when present.',generated_video_sec=0,sound_cue='Same approved Aaron PVC settings; no artificial scientific audio.',transition_out='Clean cut preserving warm palette and caption position.',fallback='Static explanatory still.')
  elif name=='asset-plan.json':base.update(copy=title,visual_role='explanation' if i<5 else 'evidence',asset_type='generated-layout' if i<5 else 'source-screenshot',fact_ids=facts,source_ids=src,asset_path='assets/eureka-wide.jpg' if i>=4 else '../../../../tiles/aaron-video-gen/remotion/src/projects/singing-sands-full/index.tsx',status='ready',provenance='Original authored schematic, not an experimental measurement.' if i<4 else 'Kurt Moses / NPS photo; metadata grants public domain. Layer diagram original when present.',rights='owned' if i<4 else 'licensed',fallback='Static illustration with narration.',license_url=f['sources'][-1]['url'] if i>=4 else '',creator='Aaron Studio' if i<4 else 'Kurt Moses',retrieved_at='2026-09-08')
  else:base.update(title=title,role='explanation' if i<5 else 'evidence',template='sand-science-explainer' if i<5 else 'image-sequence',intensity='structured' if i<5 else 'calm',purpose='Show the explanatory relationship while preserving source/illustration distinction.',entry_mode='meaningful',entry_visual=title,first_change_sec=.5,motion_recipes=['none'],content=[title,'source label','caption'],beats=[dict(at_sec=0,visual=title,action='hold'),dict(at_sec=5,visual='Narration-synchronized change',action='hold')],prototype_required=i<5,fallback_template='image-sequence',music_cue='Narration only. Real recording returns at ending.')
  q[key].append(base)
 # Ending inherits the original final 14.5 seconds.
 for b in json.loads((old/name).read_text())[key]:
  if b['start_sec']>=59.5:
   b=copy.deepcopy(b);b['id']='end-'+b['id'];b['start_sec']=d['endStartFrame']/30+b['start_sec']-59.5;b['end_sec']=d['endStartFrame']/30+b['end_sec']-59.5;q[key].append(b)
 if name=='asset-plan.json':
  for b in q[key]:
   if b.get('asset_path','').startswith('assets/') and not (p/b['asset_path']).exists():b['asset_path']='../'+old.name+'/'+b['asset_path']
 write(name,q)
# Full script preserves the pilot takes, without repeating its superseded research bridge.
original=(old/'youtube-script.md').read_text();intro=original.split('## [SLIDE: Listen again')[0];ext=(p/'extension/youtube-script.md').read_text().split('\n',1)[1].replace('## [HOOK]','## [SLIDE: Inside the sound — grains.png]');(p/'youtube-script.md').write_text(intro+'\n'+ext+'\n## [SLIDE: Listen again — sand.mp4]\nListen again. A landscape we think of as silent, making itself heard.\n')
(p/'video-brief.md').write_text((p/'extension/video-brief.md').read_text())
(p/'video-treatment.md').write_text('# Selected treatment: natural documentary\n\nAuthor-approved pilot is the visual and audio reference. Preserve its first 49.233 seconds and final 14.5 seconds. Expand with 138 seconds of science narration in the same PVC profile. Flow, synchronization, experiment, selection, and layered-dune scenes use warm original diagrams. No generic bullet slides. Chinese captions and English narration remain intentionally deferred language polish.\n\nSound: actual NPS recording opens and closes; no added music. Motion is illustrative, not physically calibrated. Prototype checks cover the new 60-second science slice before full HD export.\n')
(p/'director-memo.md').write_text('# Director decisions\n\nThe grain is the recurring visual object: flowing, sharing timing, crossing an experimental channel, then being selected by size. The clapping crowd is explicitly a comparison, not a causal proof. Experimental scenes are labeled redrawings. The wide landscape comes back for the open questions and ending.\n\nInternal prototype review must verify SVG layers visible, subtitles readable, selected grains retain original dimensions, gate moves without clipping, and no source logo is included. Final new audio is technically checked; only the preserved pilot has author listening approval.\n')
(p/'asset-decision-log.md').write_text('# Asset decisions\n\nReused pilot asset-library search: curiosity desert sparse acoustic documentary. Previous music candidates did not fit; author praised actual final sound. Keep real NPS recording, no additional track.\n\nNew landscape: NPS Gallery original 1500x998, credited Kurt Moses, explicit public-domain grant in asset metadata. Full-frame inspection passed. AI grain macro inherited with provenance from pilot. Particle shapes and crowd/channel/sieve/cutaway artwork authored in React/SVG. No optional decorative sprites: grains and people carry the scientific explanation. No publisher figures, recordings, or other media copied from papers.\n')
print('Package authored')
