import React from 'react';
import {AbsoluteFill,Composition,Sequence,Freeze,registerRoot,useCurrentFrame} from 'remotion';
import {data} from './data';
import {Scene,Picture} from './extra-scenes';
import {ease,font,cream,ink} from './scenes';
import {ShortFilm,shorts} from './shorts';
const credit=(s:typeof data.scenes[number],t:number)=>{
 if(s.visual==='field')return 'FIELD FOOTAGE / NPS · Great Sand Dunes';
 if(['photo','resolve','meaning'].includes(s.visual)){const macro=s.visual==='meaning'?t<10:s.visual==='resolve'&&t>=8&&t<15;return macro?'AI ILLUSTRATION · not microscopy':'PHOTOGRAPH / Kurt Moses · NPS · Eureka Dunes';}
 if(s.visual==='gripper')return 'CONCEPT ILLUSTRATION · granular jamming';
 if(s.visual==='silo'&&t<9)return 'AI ILLUSTRATION · invented facility';
 if(s.visual==='layers'||s.visual==='burps'||s.visual==='frequency')return 'NPS PHOTOGRAPH + EXPLANATORY GRAPHIC';
 return 'EXPLANATORY ANIMATION · not experimental footage';
};
const Chapter:React.FC<{s:typeof data.scenes[number]}>=({s})=><AbsoluteFill><Picture file={s.chapter===5?'gripper.png':s.chapter===4?'silo.png':'eureka.jpg'} dark={.55}/><div style={{position:'absolute',left:120,top:320,width:1300}}><div style={{fontSize:24,letterSpacing:5,marginBottom:32,color:'#d6b782'}}>CHAPTER {String(s.chapter).padStart(2,'0')}</div><div style={{fontSize:82,lineHeight:1.1,fontFamily:'Georgia,serif'}}>{s.chapterTitle}</div></div></AbsoluteFill>;
const Shot:React.FC<{s:typeof data.scenes[number]}>=({s})=>{const local=useCurrentFrame()/30,lead=s.voiceStart-s.start;const showChapter=s.chapter>0&&local<lead;return <AbsoluteFill>{showChapter?<Chapter s={s}/>:<Sequence from={s.chapter>0?Math.round(lead*30):0}><Scene kind={s.visual}/></Sequence>}<AbsoluteFill style={{background:'linear-gradient(180deg,rgba(12,9,5,.24),transparent 24%,transparent 73%,rgba(12,9,5,.72))'}}/><div style={{position:'absolute',left:104,top:54,fontSize:20,letterSpacing:3,color:cream}}>AARON GUO <span style={{opacity:.6,letterSpacing:1}}> / FIELD NOTES 01</span></div><div style={{position:'absolute',right:104,top:54,fontSize:18,color:'#e8d7bb'}}>{showChapter?(s.chapter===5||s.chapter===4?'AI ILLUSTRATION':'PHOTOGRAPH / Kurt Moses · NPS'):credit(s,local-(s.chapter>0?lead:0))}</div>{s.id==='intro'&&local<8.5&&<div style={{position:'absolute',left:110,top:245,fontFamily:'Georgia,serif',fontSize:91,lineHeight:1.1,opacity:1-ease(local,7.5,8.5)}}>The desert<br/>has a voice.</div>}{s.id==='intro'&&local<5&&<div style={{position:'absolute',left:110,bottom:105,fontSize:28}}>Listen first. This is a real field recording.</div>}{s.id==='listen'&&local>s.words[s.words.length-1].end-s.start+.2&&<div style={{position:'absolute',left:110,bottom:105,fontSize:28}}>Only the dune.</div>}</AbsoluteFill>};
const Film:React.FC=()=>{const t=useCurrentFrame()/30;const cap=data.captions.find(c=>t>=c.start&&t<c.end);return <AbsoluteFill style={{background:ink,color:cream,fontFamily:font}}>{data.scenes.map(s=><Sequence key={s.id} from={Math.round(s.start*30)} durationInFrames={Math.round(s.end*30)-Math.round(s.start*30)}><Shot s={s}/></Sequence>)}{cap&&<div style={{position:'absolute',left:155,right:155,bottom:66,textAlign:'center',fontSize:39,fontWeight:500,lineHeight:1.35,textShadow:'0 2px 8px #000,0 0 24px #000'}}>{cap.text}</div>}{t>=data.endCardStart&&<AbsoluteFill style={{background:ink,justifyContent:'center',alignItems:'center',opacity:ease(t,data.endCardStart,data.endCardStart+.5)}}><div style={{fontFamily:'Georgia,serif',fontSize:74}}>Aaron Guo</div><div style={{fontSize:24,letterSpacing:4,color:'#bea782',marginTop:24}}>FIELD NOTES · KEEP LOOKING CLOSER</div></AbsoluteFill>}</AbsoluteFill>};
const Contact:React.FC=()=> <AbsoluteFill style={{background:ink}}>{[2,65,149,200,249,310,368,445,510].map((t,i)=><div key={i} style={{position:'absolute',left:(i%3)*640,top:Math.floor(i/3)*360,width:1920,height:1080,transform:'scale(0.3333333333)',transformOrigin:'top left'}}><Freeze frame={Math.round(t*30)}><Film/></Freeze></div>)}</AbsoluteFill>;
const ShortContact:React.FC=()=> <AbsoluteFill style={{background:ink}}>{[0,1,2].flatMap(i=>[1,12,28].map((t,j)=><div key={i+'-'+j} style={{position:'absolute',left:i*360,top:j*640,width:1080,height:1920,transform:'scale(0.3333333333)',transformOrigin:'top left'}}><Freeze frame={Math.round(t*30)}><ShortFilm index={i}/></Freeze></div>))}</AbsoluteFill>;
const Root:React.FC=()=> <><Composition id="LongContact" component={Contact} durationInFrames={data.durationFrames} fps={30} width={1920} height={1080}/><Composition id="ShortContact" component={ShortContact} durationInFrames={1800} fps={30} width={1080} height={1920}/><Composition id="SingingSandsLongEn" component={Film} durationInFrames={data.durationFrames} fps={30} width={1920} height={1080}/>{shorts.map((s,i)=><Composition key={s.id} id={s.id} component={ShortFilm} defaultProps={{index:i}} durationInFrames={Math.round((s.end-s.start+2.5)*30)} fps={30} width={1080} height={1920}/>)}</>;
registerRoot(Root);
