from pathlib import Path
R=Path.cwd()
def edit(name, changes):
 p=R/name;s=p.read_text()
 for old,new in changes:
  if s.count(old)!=1: raise ValueError(f'{name}: expected one target {old[:90]!r}, got {s.count(old)}')
  s=s.replace(old,new)
 p.write_text(s)
def section(name,start,end,replacement):
 p=R/name;s=p.read_text();a=s.index(start);b=s.index(end,a);p.write_text(s[:a]+replacement+'\n\n'+s[b:])
p='tiles/blog-production/SKILL.md'
edit(p,[
 ('Use the user\'s path if provided. Otherwise choose the newest directory under `src/content/blogs/`.','Use the user\'s path or the active package from this task and `package-state.json`. Do not choose a different article merely because its directory is newer. If several packages fit and context cannot distinguish them, ask which one.'),
 ('- all files in the chosen post directory','- `package-state.json`, the current article/brief, and only the current phase\'s canonical evidence and review records; open archived drafts only for an explicit comparison'),
 ('Use the first matching missing artifact:','Resolve the requested phase and current package state first. Fix an upstream failed gate before filling downstream artifacts. The table is a routing aid, not a requirement to generate every listed output; existing authorization and explicit scope take precedence.'),
 ('| no `distribution-plan.md`, `x-post.md`, `linkedin-brief.md`, `facebook-post.md`, or `newsletter-teaser.md` | use `blog-write` package completion |\n',''),
 ('| article exists but no `canon-note.md` | use `blog-write` canon note pass |','| article exists but no `canon-note.md` | use `blog-write` canon note pass |\n| article editorial review passes and requested distribution assets are missing | use `blog-write` package completion |'),
 ('- a personal-proof plan. If the article has no proprietary data, arrange one\n  small observed check in an Aaron-owned project before drafting: baseline,\n  deterministic signal, expected result, and stop condition. Never invent a\n  personal result or turn a proposed experiment into evidence;','- an evidence path appropriate to the article\'s form. Require personal proof\n  only for a claim that depends on an unobserved personal result. Public\n  examples and clearly labeled hypotheses can support a sourced explanation;\n  never invent a personal result or present a planned experiment as evidence;'),
 ('`GO` requires a distinct operator contribution and an evidence path. `HOLD`\nis the normal result when a source is timely but Aaron has not yet observed\nthe mechanism himself.','`GO` requires a clear reader promise and an honest evidence path. Use `HOLD`\nwhen a central claim specifically needs missing personal proof; a personal\nresponse or sourced explainer does not need a mandatory experiment.'),
 ('| `editorial-scorecard.md` | editorial contract, weighted final score, and revision delta |','| `editorial-scorecard.md` | passage-linked editorial decision, checks, and revision delta |'),
 ('| `source-intake.md` | Source-first greenlight: primary-source notes, distinctness test, personal experiment, and media proof map |','| `source-intake.md` | Source-first greenlight: primary-source notes, reader promise, evidence path, and media proof map |'),
 ('- `memory-reflection.md` checks at least three prior posts when relevant and records internal link candidates or explains why no useful connection exists.','- `memory-reflection.md` records only useful prior-post connections or why none is needed; no reading quota.'),
 ('- `editorial-brief.md` names reader pain, sharp thesis, opening bottleneck, original contribution, authority boundary, evidence needed, counterargument, reusable frame, distribution hook, and kill criteria.','- `editorial-brief.md` captures author intent, reader promise, form/lead language, material and authority boundary using the shared editorial contract.'),
 ('- `argument-memo.md` maps thesis -> why now -> mechanism -> evidence -> counterargument -> reusable frame -> implication.','- `argument-memo.md` explains section jobs, the evidence path and intended landing appropriate to the chosen form; frameworks and counterarguments are included when useful.'),
 ('**Editorial contract gate** — before a serious draft or structural rewrite, write the reader, reader job, one-sentence promise, opening scene or bottleneck, original contribution, scope boundary, and success hypothesis into `editorial-scorecard.md`. Put the article\'s original judgment in the first 15% and earn the title within the first 150 words. Do not let the article mirror the research dossier or summarize companies one by one.','**Editorial contract gate** — use the single brief and form-specific standards in `references/editorial-system.md`. Keep the author\'s intent visible, give examples sufficient context and establish the title\'s promise early. Do not duplicate the brief in a separate scorecard.'),
 ('**Editorial scorecard gate** — after prose polish, score the draft using `editorial-scorecard.md`. Passing requires 85/100 or higher and no dimension below 70% of its weight. Every score needs draft evidence. Record what was added, cut, reframed, and intentionally kept. A score never overrides unsupported claims, a misleading title, broken links, or missing images.','**Editorial review gate** — after prose polish, record `Review format: evidence-v1`, passage-linked `Review evidence:`, resolved blockers and `Decision: PASS|FAIL|PENDING` in `editorial-scorecard.md`. Follow `references/editorial-system.md`; do not use a total score as proof of quality. Historical numeric records remain readable.'),
 ('npx -y bun tiles/blog-write/scripts/blog-style-quality.ts <blog-dir>/<slug>.md --require-personal-anchor --require-story-craft','npx -y bun tiles/blog-write/scripts/blog-style-quality.ts <blog-dir>/<slug>.md'),
 ('Use the report as an editorial gate for naturalness, Aaron voice, and story craft.','Use the report as a wording signal alongside a real editorial read, not as a score of naturalness or story quality. Enable personal-anchor/story heuristics only when relevant to the form.')
])
section(p,"### Aaron's default blog style",'### 2. Detect the next step',"### Aaron's voice and article form\n\nUse `references/editorial-system.md` for author intent, article form and review decisions; use `src/content/strategy/blog-writing-language.md` for prose. Keep concrete, natural writing and the author's real judgment. Personal responses, cases and explainers may have different structures; commercial value, a contrarian thesis and a framework are not universal requirements.")
section(p,'**Article depth gate**','**Prose polish gate**',"**Article depth and red-team review** — apply the passage-linked questions in `references/editorial-system.md`. Record actual blockers and reader losses in `red-team-review.md`, then revise where justified. There is no minimum issue count, mandatory extra rewrite or required operating framework. A clear no-change judgment is valid.")
p='tiles/blog-write/SKILL.md'
section(p,'Use the user\'s path if provided.','Read `src/content/strategy/x.md`',"Use the user's path or the current package established in this task and `package-state.json`. Do not switch posts based on directory recency.\n\nRead the current brief, plan, claim ledger and relevant review records. Load `tiles/blog-production/references/editorial-system.md` for substantial writing or revision; it owns the shared author-intent, form and review contract. Fill only missing information needed for this task rather than requesting approval to choose a lighter workflow.")
section(p,"### Aaron's default writing style",'### Canonical blog taxonomy',"### Aaron's writing style\n\nUse `src/content/strategy/blog-writing-language.md` for natural prose and `tiles/blog-production/references/editorial-system.md` for form and reader experience. Preserve the author's stance and feeling. Keep ideas concrete and understandable; commercial claims, fixed section sizes and reusable frameworks depend on the article, not on a universal template.")
edit(p,[('### 3. Draft the English article','### 3. Draft the lead-language article'),('- For Aaron\'s default public posts, make the thesis commercially useful and opinionated enough to disagree with.','- Let the reader understand the author\'s contribution; choose personal response, case or explanation according to the brief.'),('A structural redraft must change at least two of: opening, thesis expression, section sequence, mechanism, counterargument, framework use, or ending.','Change the structure where the diagnosis requires it; no minimum number of changes.'),('After the first English draft, do one skeptical editor pass before writing companion assets.','After the lead-language draft, review the reader experience before writing companion assets.'),('npx -y bun tiles/blog-write/scripts/blog-style-quality.ts <blog-dir>/<slug>.md --require-personal-anchor --require-story-craft','npx -y bun tiles/blog-write/scripts/blog-style-quality.ts <blog-dir>/<slug>.md'),('The scanner is a candidate detector, not a final judge, but a failing report means the article needs one revision pass before continuing.','The scanner is a wording-signal detector, not a final judge. Review flags in context and revise genuine problems; use optional personal/story heuristics only when relevant to the form.'),('- a conclusion that advances the thesis instead of summarizing.','- a conclusion that completes the expression; brief synthesis, changed judgment or grounded emotion can provide closure.'),('Record at least five issues and complete at least one substantive revision before proceeding. A substantive revision changes argument, evidence, structure, rhythm, or the ending. It is not only wording polish.','Record genuine issues with passage evidence and the effect on the reader. Revise when warranted; no minimum issue count or mandatory revision. A supported no-change result is valid.')])
section(p,'Score the article against this checklist:','When reporting completion,',"Apply the shared editorial review in `tiles/blog-production/references/editorial-system.md`: author intent, context and evidence, section contribution, natural voice, and a complete ending. Use the selected article form to decide whether mechanisms, counterarguments or frameworks help. Record the passages and reasons; do not assign an aggregate quality score. Revise only diagnosed weaknesses.")
p='tiles/blog-outline/SKILL.md'
edit(p,[("Otherwise inspect the newest blog directory under `src/content/blogs/` and choose the best available source in this order:","Otherwise use the active package from this task and `package-state.json`; do not select by recency alone. Choose the relevant source in this order:"),('The memo must map thesis -> why now -> mechanism -> evidence -> counterargument -> reusable frame -> implication.','Adapt the memo to the selected form in the shared editorial contract; mechanism, counterargument and framework sections are optional when they do not help the reader.'),('用一句足够具体、可以被聪明读者反驳的话写清楚。','写清本篇想表达的判断或变化，不强制反常识或可反驳论点。'),('Prefer 5-7 sections for a 1,500-2,500 word post. Use a tighter 3-section outline for short posts.','Choose section count and length by the material. Each part must add something; merge repetitive points.'),('For Aaron\'s default style, set `Tone` to something like: "Entrepreneurial, crisp, insight-led, commercially useful; no soft self-help, literary emotion, or teacherly advice."','Set tone from the author\'s intent and language strategy. Preserve grounded enthusiasm, concern or reflection when it belongs to the article.'),('- The personal anchor is concrete.','- Personal experience, sourced examples and hypothetical illustrations are clearly distinguished.'),('- The outline names the business value or strategic implication, not only a personal feeling.','- The outline delivers the selected form\'s reader promise and preserves the author\'s attitude.'),('<One sentence. Specific enough that someone could disagree.>','<The main judgment or change this article helps the reader understand.>'),('<The lived experience, project, experiment, or observation that makes this Aaron\'s piece.>','<Relevant experience or author stance; public examples remain attributed to their source.>')])
section(p,"Read the 2-3 most recent finished English posts",'### 2b. Build The Argument Memo',"Read `tiles/blog-production/references/editorial-system.md` and `src/content/strategy/blog-writing-language.md`. Use the brief's author intent and article form. If a recurring expression problem needs calibration, read one relevant example from `tiles/blog-production/references/editorial-examples.md`. Read prior posts only when they help the current article; do not force a callback or copy a previous structure.\n\nKeep private project context local; never copy private Brain content into web tools.")
p='tiles/blog-brainstorm/SKILL.md'
section(p,'### Step 2b: Memory Reflection','### Step 3: Research Trending Topics',"### Step 2b: Author Intent And Relevant Memory\n\nRead `tiles/blog-production/references/editorial-system.md`. Capture author intent, reader promise, form/lead language and evidence boundaries in the existing `editorial-brief.md`. Ask only for missing details that would materially change the article.\n\nConsult earlier posts only if they help explain a changed idea or provide relevant evidence. In `memory-reflection.md`, record the useful connection or that none is needed; no reading quota or compulsory continuity thesis.")
edit(p,[('Perform **6-10 web searches** using `WebSearch` across multiple sources. Always include the current year and month for freshness.','Research until the current reader promise has sufficient evidence. For time-sensitive work, verify dates and use current sources; do not use a fixed search quota. The following source patterns are options, not required searches.'),('**For each search, extract:**','**From relevant results, extract:**'),('**Hook (first tweet):** [Draft an actual hook using one of these formulas:\n  - "I [did surprising thing]. Here\'s what happened:"\n  - "Most [role] get [topic] wrong. Here\'s why:"\n  - "[Number] lessons from [specific experience]:"\n  - "I spent [time] building [thing]. Here\'s the breakdown:"\n  - "Stop [common mistake]. Do this instead:"]','**Hook:** [Name the subject and offer a concrete, supportable reason to read. Match the author\'s voice; do not force a formula or an invented first-person experience.]'),('**Your angle:** [How this connects to your expertise/experience — use "I built/did/learned" framing]','**Your angle:** [The author\'s genuine connection, judgment or useful interpretation; do not invent experience.]'),('**Voice rule:** Use "I" not "you should." Share what I did, not what others should do.','**Voice rule:** Preserve the author\'s stance. First-person experience must be real; source-backed interpretation is also valid.'),('**This post\'s personal anchor:** [The specific personal experience/build/result this post is grounded in]','**This post\'s material:** [Real experience, source-backed examples and author judgment, clearly distinguished]'),('- Blog CTA: newsletter signup','- Blog CTA: optional if it fits the ending')])
section(p,'`editorial-brief.md` must include:','`research-dossier.md` is an internal review artifact',"`editorial-brief.md` follows the single author-intent and reader-promise contract in `tiles/blog-production/references/editorial-system.md`. Include only the thesis, objections, mechanisms and reusable frames that the chosen form needs. Do not require every article to be a commercial argument.")
p='tiles/blog-prose-editor/SKILL.md'
edit(p,[('- `argument-memo.md`','- `editorial-brief.md` for author intent and form\n- `argument-memo.md`'),('npx -y bun tiles/blog-write/scripts/blog-style-quality.ts <blog-dir>/<slug>.md --require-personal-anchor --require-story-craft','npx -y bun tiles/blog-write/scripts/blog-style-quality.ts <blog-dir>/<slug>.md'),('7. Hand the polished files back to the editorial scorecard pass. Do not mark `editorial-scorecard.md` as passing merely because the language scanner passes.','7. Apply the passage-linked review in `tiles/blog-production/references/editorial-system.md`. Treat scanner flags as wording signals; enable personal/story heuristics only where relevant. Record the author-intent and ending judgment, not an aggregate quality score.')])
p='src/content/strategy/blog-writing-language.md'
edit(p,[("The goal is to publish work that has concrete experience, sharp claims, natural rhythm, and commercial usefulness.","The goal is to publish work with concrete material, clear author judgment and natural rhythm. Commercial usefulness matters when it serves this article's purpose.")])
section(p,'A strong Aaron post usually has:','### 直接陈述优先于自造标签',"Use `tiles/blog-production/references/editorial-system.md` for form-specific editorial judgment. Shared voice qualities are concrete material, enough context for the reader, natural paragraph movement and an ending that completes the author's thought. Personal responses may be reflective; cases may be technical; explainers may rely on public evidence. Do not force all of them into an operating framework or a contrarian commercial thesis.\n\nWhen a revision improves the prose, record the passage and why it works. Select examples for clarity and fidelity to the author's intent, not merely for dates, numbers or first-person keywords.")
print('Updated shared contract references and removed conflicting editorial requirements.')
