from pathlib import Path
import json,re,math,shutil
P=Path(__file__).resolve().parents[1]; ROOT=P.parents[3]; OUT=ROOT/'tiles/aaron-video-gen/remotion/src/projects/code-upstream'; PUB=ROOT/'tiles/aaron-video-gen/remotion/public/code-upstream'
OUT.mkdir(parents=True,exist_ok=True);PUB.mkdir(parents=True,exist_ok=True)
m=json.loads((P/'audio-generation-manifest.json').read_text());segments=m['timeline']['segments'];words=m['timeline']['wordTimings'];scenes=[];shift=3.;duration=math.ceil((m['qa']['durationSeconds']+shift+5)*30)/30
clean=lambda s:re.sub('[^a-z0-9]','',s.lower())
def at(idx,phrase):
 seg=segments[idx];target=[clean(x) for x in phrase.split()];pool=[w for w in words if seg['start']-.001<=w['start']<seg['end']];vals=[clean(w['word']) for w in pool]
 for k in range(len(vals)-len(target)+1):
  if vals[k:k+len(target)]==target:return pool[k]['start']
 raise ValueError((idx,phrase))
def add(a,b,kind,title,sub='',nodes=None,media=None,facts=None,sources=None,rail=None,tension=False):
 scenes.append(dict(id=f's{len(scenes):02}',start=round((a+shift)*30)/30,end=round((b+shift)*30)/30,kind=kind,title=title,sub=sub,nodes=nodes or [],media=media,facts=facts or [],sources=sources or [],rail=rail or ('CONCEPTUAL ILLUSTRATION' if media else 'AARON GUO · PERSONAL JUDGMENT'),tension=tension))
def split(idx,cuts,items):
 bounds=[segments[idx]['start']]+[at(idx,c) for c in cuts]+[segments[idx]['end']]
 for k,item in enumerate(items):add(bounds[k],bounds[k+1],**item)
def s(kind,title,sub='',**kw):return dict(kind=kind,title=title,sub=sub,**kw)
scenes.append(dict(id='s00',start=0.,end=3.,kind='cover',title='BUILD WHAT MATTERS',sub='AI and the next move for engineers',nodes=[],media='thumbnail.jpg',facts=[],sources=[],rail='CONCEPTUAL ILLUSTRATION',tension=False))
judgment=dict(facts=['author-judgment'],rail='AARON GUO · PERSONAL JUDGMENT')
hyp=dict(facts=['hypothetical-tool'],rail='HYPOTHETICAL DOCUMENT TOOL · NOT AN OBSERVED RESULT')
split(0,['That judgment stayed'],[s('compare','A judgment from my years at Amazon.','A company’s ability to fund roles is different from the need it serves.',nodes=['Organizational capacity\nJobs it can afford','Business need\nValue it must create'],**judgment),s('media','Where does the work\nbecome useful?','A career question, made more pressing by stronger execution tools.',media='cover.png',**judgment)])
split(1,['Someone can work'],[s('row','An organization can create its own work.','Customer needs may grow much more slowly.',nodes=['More layers','More coordination','More internal work'],**judgment),s('statement','Hard work can be absorbed internally.','That shaped how I read the later restructuring.',**judgment)])
amazon=dict(facts=['amazon-statements'],sources=['amazon-structure-2024','amazon-ai-2025','amazon-roles-2026'],rail='AMAZON · PUBLIC STATEMENTS · 2024 / 2025 / JAN 2026')
split(2,['The following year','Its January'],[s('row','2024 / Reduce layers.','Amazon’s stated organizational priorities.',nodes=['Fewer layers','Fewer unnecessary processes'],**amazon),s('statement','2025 / An AI workforce forecast.','Andy Jassy expected a smaller total corporate workforce over time.',**amazon),s('compare','2026 / Restructuring continued.','An announcement cannot establish an individual’s contribution.',nodes=['Public statement\nFewer layers, less bureaucracy','Interpretation boundary\nNo verdict on a person'],**amazon)])
split(3,['For the next'],[s('statement','Cheaper execution changes the calculation.','My interpretation: it accelerates organizational reassessment.',**judgment),s('media','Invest in the work\naround the code.','Customers. Product choices. Work that reaches use.',media='cover.png',**judgment)])
pract=dict(facts=['practitioner-examples'],sources=['boris-video','simon-video'],rail='BORIS CHERNY / SIMON WILLISON · PERSONAL PRACTICES')
split(4,['These are particular'],[s('compare','Two ways implementation is changing.','Their own practices, with human judgment still involved.',nodes=['Boris Cherny\nAI writes; he reviews','Simon Willison\nTry alternative prototypes'],**pract),s('statement','What deserves the effort?','Cheaper trials give us room to ask a better question.',**pract)])
split(5,['Kent Beck','Keep learning'],[s('row','1 / Learn an industry deeply.','The business gives the feature its meaning.',nodes=['Who uses it?','Who pays?','Who bears the risk?']),s('compare','Payroll is more than a calculation.','Kent Beck’s example: visible functionality and broader responsibility.',nodes=['Visible feature\nCalculate an amount','Business context\nObligations behind it'],facts=['payroll-example'],sources=['kent-video'],rail='KENT BECK × GERGELY OROSZ · INTERVIEW PARAPHRASE'),s('statement','Notice needs before they become tickets.','Build that understanding across real projects.')])
split(6,['But when you watch'],[s('row','2 / Spend time with customers.','Our document tool is a hypothetical example.',nodes=['A beautiful demo','Accurate-looking fields'],**hyp),s('media','Watch the pause.','An exception. A missing confirmation. A result they do not trust.',media='customer.png',**hyp)])
split(7,['You may discover'],[s('row','Follow the exception.','Let the user show the current workflow.',nodes=['Who checks?','How is it corrected?','What must keep working?'],**hyp),s('statement','Observation changes the next feature.','Use some of the saved time to go back and learn.',**hyp)])
split(8,['For our imagined'],[s('media','3 / Practice product decisions.','Use cheaper implementation to compare possibilities.',media='alternatives.png',facts=['prototype-practice'],sources=['simon-video'],rail='WILLISON: ALTERNATIVES + USABILITY ADVICE · ILLUSTRATION'),s('compare','Two approaches. One user task.','Watch hesitation and task completion before choosing.',nodes=['Approach A\nVerify every item','Approach B\nHighlight exceptions'],**hyp)])
split(9,['This is how'],[s('statement','What should this experiment answer?','Write the question before building.'),s('row','A basis for choosing.', 'Product judgment grows through repeated decisions.',nodes=['What belongs?','What can wait?','What does the business require?'])])
split(10,['Money is one cost','Understand why'],[s('statement','4 / Test commercial value.','A useful product still asks someone to change.'),s('row','Adoption has a cost.','Include the change the customer must make.',nodes=['Money','Learning','Integration','Trust']),s('media','Why would\nsomeone switch?','A working prototype gives the conversation substance.',media='customer.png')])
split(11,['Include model usage'],[s('row','Take the idea into the market.','Concrete commitments teach more than vague enthusiasm.',nodes=['Try it?','Integrate it?','Budget for it?']),s('compare','Revisit what was once too expensive.','Let contact with the market shape what continues.',nodes=['Cost estimate\nModels, upkeep, support','Customer evidence\nTime, adoption, alternatives'])])
split(12,['It later brought'],[s('statement','5 / Follow the project into use.','Microsoft Digital: faster individuals did not initially mean a faster team.',facts=['microsoft-practice'],sources=['microsoft'],rail='MICROSOFT DIGITAL · SEPT 3, 2026 · ORGANIZATIONAL SELF-REPORT'),s('flow','Connect the work.','Business intent and acceptance criteria belong in shared understanding.',nodes=['Intent','Shared specification','Acceptance'],facts=['microsoft-practice'],sources=['microsoft'],rail='MICROSOFT DIGITAL · PARAPHRASE, NOT INDEPENDENT BENCHMARK')])
split(13,['I recently used','Engineering experience'],[s('flow','Make completion meaningful.','Follow the work through the user’s first real attempt.',nodes=['Agree on goal','Check failures','Help them start','Return for feedback']),s('statement','I am more willing to carry a whole task.','One cross-system reporting task; verified in development.',facts=['report-experience'],rail='AARON’S EXPERIENCE · DEVELOPMENT VERIFICATION'),s('statement','Make the result trustworthy.','Engineering experience has a place in the whole delivery.')])
split(14,['Each project'],[s('compare','Keep ability connected to real needs.','The judgment from Amazon still shapes my choices.',nodes=['An organization\nCan provide a role','My responsibility\nKeep learning what is useful'],**judgment),s('flow','Let each project build your judgment.','A customer, a product choice, a result in use.',nodes=['Understand','Choose','Deliver','Learn'])])
split(15,['That growth','Stronger tools'],[s('statement','What will you understand in ten years?','I want a deeper understanding of what people need.'),s('row','Begin with the next project.','Capability grows through contact and follow-through.',nodes=['A conversation','A product experiment','A complete project']),s('media','Make things you care about.','Things someone else actually needs.',media='used.png')])
scenes.append(dict(id=f's{len(scenes):02}',start=scenes[-1]['end'],end=duration,kind='end',title='AARON GUO',sub='AI-NATIVE BUILDER · Human-first thinker',nodes=[],media=None,facts=[],sources=[],rail='',tension=False))
captions=[];group=[]
for w in words:
 group.append(w)
 if (re.search(r'[.!?,;:]$',w['word']) and len(group)>=4) or len(group)>=10:
  captions.append(dict(start=group[0]['start']+shift,end=group[-1]['end']+shift,text=' '.join(x['word'] for x in group)));group=[]
if group:captions.append(dict(start=group[0]['start']+shift,end=group[-1]['end']+shift,text=' '.join(x['word'] for x in group)))
media_paths={'cover.png':'imgs/00-cover-v2.png','thumbnail.jpg':'imgs/thumbnail-youtube-v2.jpg','customer.png':'imgs/01-watch-the-work-v2.png','alternatives.png':'imgs/02-choose-the-path-v2.png','used.png':'imgs/03-used-in-the-world-v2.png'}
for n,path in media_paths.items():shutil.copy2(P/path,PUB/n)
shutil.copy2(ROOT/'assets/aaron-logo-assets/ag-logo.png',PUB/'ag-logo.png')
for x in scenes:
 d=x['end']-x['start'];x['cues']=[round(v,3) for v in ([.5]+[min(d-.5,3+i*4) for i in range(max(len(x['nodes'])-1,0))])];x['detailCue']=min(1.,d*.2)
data=dict(duration=duration,fps=30,audioOffset=shift,scenes=scenes,captions=captions)
(OUT/'data.ts').write_text('export const filmData = '+json.dumps(data,ensure_ascii=False,indent=2)+';\n');(P/'video-production/timeline.json').write_text(json.dumps(data,ensure_ascii=False,indent=2)+'\n')
ref=dict(baseline_id='ledger-editorial-v1',reference_package='src/content/blogs/2026-08-19',reference_video='src/content/blogs/2026-08-19/video-v3.mp4',reference_qa='src/content/blogs/2026-08-19/video-qa-report.md',inherited_system='Ivory paper, graphite typography, registered layout geometry, protected captions, evidence rails, semantic focus; Astra accepted renderer and DHH music restraint inform this continuation.',rejected_legacy_pattern='Full-frame illustration slideshow, blank title stages, repeated card grids, decorative camera drift.',deliberate_deviation='Author retains tactile paper style; V2 replaces ambiguous couple/domestic imagery with business-document work and defined professional actions. Narration, layouts, timing and motion are unchanged.',review_status='reviewed')
director=dict(schema_version=1,title='AI and the next move for engineers',duration_sec=duration,product_promise='Five investments in business and product judgment as implementation gets cheaper.',style_reference=ref,visual_budget=dict(remotion_motion_target_ratio=.7,evidence_or_still_target_ratio=.3,max_generated_video_ratio=0,max_generated_video_beats=0,max_semantic_sprite_beats=0),beats=[])
board=dict(schema_version=1,title=director['title'],duration_sec=duration,fps=30,direction=dict(name='Work that reaches people',style_family_id='ledger-editorial-v1',visual_spine=ref['inherited_system'],motion_density='balanced',music_strategy='chaptered',references=[dict(id='ledger',url='https://youtu.be/5vEEBhbfUWw',borrow=ref['inherited_system'],avoid=ref['rejected_legacy_pattern'])]),scenes=[])
assets=dict(schema_version=1,title=director['title'],duration_sec=duration,aspect_ratio='16:9',visual_spine_id='ledger-editorial-v1',asset_library=dict(queries=['calm piano','Paper Moon'],selected_asset_ids=['music:b161e820cd4f5741']),beats=[])
for x in scenes:
 k=x['kind'];d=x['end']-x['start'];role='emphasis' if k in ['cover','statement','end'] else 'explanation';mode='hybrid' if k=='media' else 'generated-still' if k=='cover' else 'motion';template='image-sequence' if k in ['cover','media'] else 'brand-end-card' if k=='end' else 'editorial-statement' if k=='statement' else 'system-map';intensity='calm' if k in ['cover','media','statement','end'] else 'structured';recipe='focus-shift' if intensity=='structured' or k=='statement' else 'crossfade';change=.25 if k=='cover' else 0. if k=='end' else 1. if k in ['media','statement'] else 2.4 if k=='flow' else .5
 content=[v for v in [x['title']]+x['nodes']+[x['sub']] if v];beats=[dict(at_sec=0,visual=x['title'],action='Readable scaffold at entry'),dict(at_sec=change,visual=x['sub'] or x['title'],action='Support emphasis or first structural focus')]
 for i,c in enumerate(x['cues'][1:],1):beats.append(dict(at_sec=c,visual=x['nodes'][i],action='Move focus to the next visible concept'))
 if d>12:beats.append(dict(at_sec=min(d-1,12),visual=x['sub'],action='Intentional reading hold while the spoken example completes; no invented extra animation'))
 board['scenes'].append(dict(id=x['id'],title=x['title'],start_sec=x['start'],end_sec=x['end'],role=role,template=template,intensity=intensity,purpose='Make the spoken decision legible: '+x['title'],entry_mode='meaningful',entry_visual=x['title'],first_change_sec=change,motion_recipes=[recipe],content=content,beats=beats,music_cue='Sparse chapter cues; constant voice gain.',prototype_required=False,fallback_template='image-sequence'))
 director['beats'].append(dict(id=x['id'],start_sec=x['start'],end_sec=x['end'],narrative_role='hook' if k=='cover' else 'resolve' if k=='end' else 'explain',visual_mode=mode,intensity=intensity,entry_mode='meaningful',entry_visual=x['title'],first_visual_change_sec=change,visual_reason='One reading job: '+x['title'],camera_or_motion=recipe+' inside registered geometry; no camera drift.',asset_id=x['id'],asset_provenance=x['rail'] or 'Owned author identity',generated_video_sec=0,sound_cue='Chapter cue only where specified in sound plan.',transition_out='Clean cut preserves paper field and caption region.',fallback='Readable static composition'))
 assets['beats'].append(dict(id=x['id'],start_sec=x['start'],end_sec=x['end'],copy=' / '.join(content),visual_role=role,asset_type='generated-still' if x['media'] else 'generated-layout',fact_ids=x['facts'],source_ids=x['sources'],asset_path=media_paths.get(x['media']),usage_role='primary',status='ready',provenance=x['rail'] or 'Owned typography',rights='generated' if x['media'] else 'owned',editorial_approval=None,fallback='Native type preserves the claim and source boundary.'))
for name,obj in [('director-plan.json',director),('video-storyboard.json',board),('asset-plan.json',assets)]: (P/name).write_text(json.dumps(obj,ensure_ascii=False,indent=2)+'\n')
def fmt(t):
 ms=round(t*1000);return f'{ms//3600000:02}:{ms//60000%60:02}:{ms//1000%60:02},{ms%1000:03}'
(P/'video-captions-en.srt').write_text('\n\n'.join(f'{i+1}\n{fmt(c["start"])} --> {fmt(c["end"])}\n{c["text"]}' for i,c in enumerate(captions))+'\n')
print(f'{len(scenes)} scenes, {len(captions)} captions, {duration:.3f} seconds')
