from pathlib import Path
import json,datetime,hashlib
p=Path(__file__).resolve().parent;root=p.parents[3];old=p.parent/'singing-sands-full-2026-09-08';d=json.loads((p/'timeline.json').read_text());now=datetime.datetime.now(datetime.timezone.utc).isoformat()
def write(n,x):(p/n).write_text(json.dumps(x,indent=2)+'\n')
f=json.loads((old/'fact-pack.json').read_text());f['thesis']='Understand a real dune sound, distinguish experimental questions, and explore bounded links to granular engineering.'
extra=[('air','https://openstax.org/books/university-physics-volume-1/pages/17-1-sound-waves','OpenStax University Physics','Longitudinal pressure disturbances and local air particle oscillation.'),('silos','https://arxiv.org/abs/cond-mat/0310086','Muite et al., Powder Technology 2004','Silo sound/vibration and wall-grain stick-slip; DOI 10.1016/j.powtec.2004.07.003. Publisher abstract and Princeton record corroborate.'),('gripper','https://arxiv.org/abs/1009.4444','Brown et al., PNAS 2010','Vacuum-induced granular jamming gripper. DOI 10.1073/pnas.1003250107.'),('gripper-release','https://news.cornell.edu/stories/2012/02/robotic-gripper-can-now-throw-things','Cornell Chronicle, 2012','Subsequent gripper demonstration clarifies release through pressure reversal.'),('waves-2015','https://authors.library.caltech.edu/records/b3tan-cab83','Vriend et al., Physics of Fluids 2015','70–105 Hz at investigated sites; burping versus booming wave modes; DOI 10.1063/1.4931971.')]
for id,url,pub,note in extra:f['sources'].append(dict(id=id,url=url,publisher=pub,source_type='primary',verification_status='verified',rights='public-source',notes=note))
newclaims=[('f10','Sound in air propagates as pressure disturbances while air particles oscillate locally.',['air'],'Diagram is slow and symbolic, not a measured molecular simulation.'),('f11','Silo studies measured discharge-driven vibration and sound linked to stick-slip wall friction in tall narrow silos.',['silos'],'Related engineering domain; not claimed identical to dune acoustics.'),('f12','A flexible bag of granular material can conform to an object and become more rigid under vacuum to grip it.',['gripper','gripper-release'],'Related granular physics, not a direct invention from singing-dune research.'),('f13','The 2015 field study distinguished brief burps and sustained booming and reported 70–105 Hz peaks at investigated sites.',['waves-2015'],'Do not universalize frequency range or present waveguide interpretation as the only explanation.'),('f14','Pitch, loudness and spectral concentration are different sound properties.',['air','dagois-2012'],'Selecting grain sizes does not resize grains or simply imply increased loudness.')]
for id,claim,src,bound in newclaims:f['facts'].append(dict(id=id,claim=claim,source_ids=src,confidence='high',usable_in_script=True,sensitivity=bound))
write('fact-pack.json',f)
r=json.loads((old/'research-evidence.json').read_text());r.update(bundle_id=p.name,topic='Singing sands long film and English short-form derivatives',created_at=now);r['producer']['run_id']=p.name
for id,url,pub,note in extra:r['sources'].append(dict(id=id,type='web',canonical_url=url,title=pub,retrieved_at=now,access_method='public_web',limitations=[note],transcript={'status':'not_applicable'}))
for id,claim,src,bound in newclaims:r['claims'].append(dict(id=id,kind='source_fact',text=claim,source_ids=src,verification_status='verified',confidence='high'))
r['claims'].append(dict(id='applications-link',kind='inference',text='These examples connect through granular physics; direct derivation from dune-acoustics research is not established.',source_ids=['silos','gripper'],verification_status='verified',confidence='high'))
r['coverage']['notes']=['Bounded documentary source review, not an exhaustive literature review.','No direct commercial spin-off of singing sand is asserted.','Pure English narration, captions and display text; Chinese edition is a separate future variant.','New score and narration remain author-review candidates.'];write('research-evidence.json',r)
ref=dict(baseline_id='sand-documentary-author-approved-full',reference_package=str(old.relative_to(root)),reference_video=str((old/'film.mp4').relative_to(root)),reference_qa=str((old/'video-qa-report.md').relative_to(root)),inherited_system='Warm documentary images, real sand recording, calm explanation, approved voice profile and retained takes, stable subtitles.',rejected_legacy_pattern='Generic text-heavy slide deck and mixed-language overlays.',deliberate_deviation='Author requested 7–8 minutes or longer, applications, chapter music, demonstration scoring, separate languages and short-form derivatives.',review_status='reviewed')
plan=dict(schema_version=1,title='The desert has a voice',duration_sec=d['durationFrames']/30,product_promise=f['thesis'],style_reference=ref,visual_budget=dict(remotion_motion_target_ratio=.55,evidence_or_still_target_ratio=.45,max_generated_video_ratio=0,max_generated_video_beats=0,max_semantic_sprite_beats=0),beats=[])
ast=dict(schema_version=1,title=plan['title'],duration_sec=plan['duration_sec'],aspect_ratio='16:9',visual_spine_id='sand-documentary-en-v2',asset_library=dict(queries=['documentary warm sparse piano marimba acoustic ambient'],selected_asset_ids=[]),beats=[])
st=dict(schema_version=1,title=plan['title'],duration_sec=plan['duration_sec'],fps=30,direction=dict(name='Warm English documentary',style_family_id='sand-documentary-en-v2',visual_spine='Actual sand, tactile illustrations, original explanatory diagrams, quiet English captions.',motion_density='balanced',music_strategy='chaptered',references=[dict(id='nps',url=f['sources'][0]['url'],borrow='Immediate field sound and actual sand motion.',avoid='Institutional title overlays.')]),scenes=[])
lookup={'intro':['f1','f2'],'avalanche':['f1','f4'],'conditions':['f3'],'note':['f13'],'flow':['f6'],'sync':['f6'],'air':['f10'],'lab':['f7'],'method':['f7'],'sort':['f8'],'pitch':['f14'],'debate':['f9'],'later':['f13'],'questions':['f9'],'silo':['f11'],'engineering':['f11'],'gripper':['f12'],'meaning':['f6','f12'],'resolve':['f6','f9'],'listen':['f1','f2']}
for s in d['scenes']:
 ids=lookup[s['id']];src=list(dict.fromkeys(a for fact in f['facts'] if fact['id'] in ids for a in fact['source_ids']));visual=s['visual'];photographic=visual in ['field','photo','resolve','meaning'];role='evidence' if visual in ['field','photo'] else 'explanation';base=dict(id=s['id'],start_sec=s['start'],end_sec=s['end']);pbeat=dict(base,narrative_role='hook' if s['id']=='intro' else 'resolve' if s['id'] in ['resolve','listen'] else 'explain',visual_mode='source-evidence' if visual=='field' else 'hybrid',intensity='calm' if photographic else 'structured',entry_mode='meaningful',entry_visual=s['title'],first_visual_change_sec=.5,visual_reason='Show the described relationship or provide a real-world visual reset with visible source/illustration labels.',camera_or_motion='Scene-clock motion; bounded grain positions and gate lift, pressure oscillation, sieve removal, and gripper state change. Image shots are static.',asset_id=s['id'],asset_provenance='NPS field evidence, attributed photography, or explicitly labeled original illustration.',generated_video_sec=0,sound_cue='Real recording at opening/close; scored chapter bridge and voice-driven music ducking in the body.',transition_out='Clean cut, retaining palette and caption position.',fallback='Static evidence photograph or explanatory still.')
 plan['beats'].append(pbeat)
 path='../singing-sands-pilot-2026-09-08/assets/sand-detail.mp4' if visual=='field' else '../singing-sands-full-2026-09-08/assets/eureka-wide.jpg' if visual=='photo' else 'assets/gripper.png' if visual=='gripper' else 'assets/silo.png' if visual=='silo' else '../../../../tiles/aaron-video-gen/remotion/src/projects/singing-sands-long/extra-scenes.tsx'
 asset_type='source-video' if visual=='field' else 'source-screenshot' if visual=='photo' else 'generated-still' if visual in ['gripper','silo'] else 'generated-layout'
 ast['beats'].append(dict(base,copy=s['title'],visual_role=role,asset_type=asset_type,fact_ids=ids,source_ids=src,asset_path=path,status='ready',provenance='NPS public-domain recording or credited photograph.' if role=='evidence' else 'Original explanatory artwork; not field evidence or calibrated measurement.',rights='licensed' if role=='evidence' else 'owned',license_url=f['sources'][0]['url'] if visual=='field' else 'https://npgallery.nps.gov/AssetDetail/ae8d30f9-0da0-42bf-9adb-b2382c85b117' if visual=='photo' else '',creator='National Park Service' if visual=='field' else 'Kurt Moses' if visual=='photo' else 'Aaron Studio',retrieved_at=now,source_start_sec=7.5 if visual=='field' else 0,source_end_sec=14.5 if visual=='field' else 0,editorial_approval='not-required',fallback='Static explanatory still with unchanged audio.'))
 template='image-sequence' if photographic else 'sand-science-longform';beats=[dict(at_sec=0,visual=s['title'],action='hold')]
 for moment in [3,7,12,18,25,32,40]:
  if moment<s['end']-s['start']-1:beats.append(dict(at_sec=moment,visual='Narration-aligned caption, state change, or ongoing explanatory process',action='hold'))
 st['scenes'].append(dict(base,title=s['title'],role=role,template=template,intensity=pbeat['intensity'],purpose=pbeat['visual_reason'],entry_mode='meaningful',entry_visual=s['title'],first_change_sec=.5,motion_recipes=['none'],content=[s['title'],'source label','caption'],beats=beats,prototype_required=False,fallback_template='image-sequence',music_cue=pbeat['sound_cue'],transform_envelope=dict(max_translation_px=260,max_rotation_deg=13,protected_caption_top_px=930)))
end=dict(id='end-card',start_sec=d['endCardStart'],end_sec=plan['duration_sec']);plan['beats'].append(dict(plan['beats'][-1],**end,narrative_role='resolve',visual_mode='motion',entry_visual='Aaron Guo / Field Notes',asset_id='end-card'));ast['beats'].append(dict(ast['beats'][-1],**end,asset_type='generated-layout',visual_role='emphasis',asset_path='../../../../tiles/aaron-video-gen/remotion/src/projects/singing-sands-long/index.tsx',rights='owned',provenance='Original author end card.'));st['scenes'].append(dict(st['scenes'][-1],**end,title='Aaron Guo',role='emphasis',template='brand-end-card',prototype_required=False,content=['Aaron Guo','Field Notes'],beats=[dict(at_sec=0,visual='Author identity',action='hold')],motion_recipes=['crossfade']))
write('director-plan.json',plan);write('asset-plan.json',ast);write('video-storyboard.json',st)
manifest={'inherited_manifests':['../singing-sands-pilot-2026-09-08/asset-manifest.json','../singing-sands-full-2026-09-08/asset-manifest.json'],'new_images':[],'music_manifest':'music/generation-manifest.json','music_cues':'music/cues.json'}
for name in ['gripper','silo']:manifest['new_images'].append(dict(file=f'assets/{name}.png',sha256=hashlib.sha256((p/f'assets/{name}.png').read_bytes()).hexdigest(),source='OpenAI image generation',role='Explicitly labeled conceptual illustration, not experimental evidence'))
write('asset-manifest.json',manifest)
(p/'video-treatment.md').write_text('# Selected treatment\n\nThe author selected the 3:22 documentary direction and requested a longer, deeper film. The pure-English edition is 8:57 after measured narration, six 3-second chapter bridges and a short ending. Keep the accepted voice and original takes; expand the questions, controlled experiment, acoustic distinctions and bounded engineering connections.\n\nTwo alternatives considered: padding existing diagrams with longer holds was rejected because it adds no information; an entirely new high-energy explainer was rejected because the author praised the existing pacing. Selected: expand the substance, add tactile images and pressure/silo/gripper explanations, and give chapters a restrained instrumental introduction.\n\nMusic has three jobs: a small question at chapter entry; a low investigative pulse under demonstrations; a warmer return before the final actual recording. A 180-second original cue is edited into different source ranges and ducked from narration. Keep the final real recording unscored. New score is a listening candidate, not automatically approved by technical metrics.\n')
(p/'director-memo.md').write_text('# Direction and motion contract\n\nExisting 3:22 film is author-approved. Pure English narration, captions, diagrams and chrome are required. No paragraph translation overlay. Grains are essential scene media, not decorative sprite accents. Original drawings are always labeled. Generated silo and gripper images are explicitly illustrations.\n\nNew pressure particles oscillate about fixed origins; the pattern travels. A sieve removes out-of-range grains without resizing the remainder. Gripper vacuum stage follows conforming; jam state precedes lift. Gate translation is bounded to 245 px; silo vibration is limited to 2 px. Captions occupy the bottom 150 px and never transform with diagrams.\n\nPrototype includes the new silo/gripper chapter and scored transitions. Inspect remaining scene entry/peak/exit stills, then promote only this bounded project capability. Avoid claiming a physical simulation. Vertical derivatives receive dedicated titles, graphics and captions; reuse exactly selected long-form audio spans.\n')
(p/'asset-decision-log.md').write_text('# Asset choices\n\nLibrary search inspected Quiet Forms, Luminous Tides and Mosslight metadata. Quiet Forms was sleep-oriented and older provenance was marked needs-verification; Luminous Tides uses nocturnal Rhodes/bass; Mosslight offers only one minute. A new original 180-second Eleven Music cue was generated with a documentary-specific wood/piano palette, phrase arc, no prominent bass drone and no artist reference. Raw prompt and song ID retained.\n\nReused NPS recording, NPS/Kurt Moses landscape and the approved AI grain macro. Added two generated conceptual stills (silo facility and jamming gripper) as tangible visual resets. They are not presented as locations or actual experiment photographs. No figures or music from scientific publications were copied.\n\nAll new illustrations were visually inspected before rendering. No optional semantic accents.\n')
# Record accepted parent before this new revision, without marking the new score accepted.
q=json.loads((old/'package-state.json').read_text());q['review']['author_feedback']='Approved overall film, voice and visual form; requested 7–8+ minute version with additional content, chapter music and short-form workflow.';q['phase']='author-approved-direction-expanded-revision-requested';(old/'package-state.json').write_text(json.dumps(q,ensure_ascii=False,indent=2)+'\n')
print('Authored package, sources',len(f['sources']),'scenes',len(st['scenes']))
