from pathlib import Path
import json,html
p=Path(__file__).resolve().parent;d=json.loads((p/'timeline.json').read_text());sources=json.loads((p/'fact-pack.json').read_text())['sources']
chapters=''.join(f'<button onclick="seek({s["start"]})"><span>{int(s["start"])//60}:{int(s["start"])%60:02d}</span> {html.escape(s["chapterTitle"])}</button>' for s in d['scenes'] if s['chapter'])
shorts=''.join(f'<article><h3>{title}</h3><video controls playsinline preload="metadata" src="shorts/{name}.mp4"></video><a download href="shorts/{name}.mp4">下载短片</a></article>' for name,title in [('SandVoiceShort','沙漠真的会唱歌'),('SandLabShort','把沙丘带进实验室'),('SandGripperShort','用颗粒做机器人抓手')])
refs=''.join(f'<li><a target="_blank" rel="noreferrer" href="{html.escape(s["url"])}">{html.escape(s["id"])} · {html.escape(s.get("publisher","Primary source"))}</a></li>' for s in sources)
page='''<!doctype html><html lang="zh-CN"><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>The desert has a voice · 8:57</title><style>*{box-sizing:border-box}body{margin:0;background:#19160f;color:#eee5d4;font:17px/1.65 system-ui,sans-serif}main{max-width:1240px;margin:auto;padding:55px 30px}h1{font:clamp(38px,5vw,66px)/1.05 Georgia,serif;margin:20px 0}h2{font-size:27px;margin-top:55px}p{max-width:850px;color:#c3b9a5}a{color:#d9b77d}video{width:100%;background:#080706;border-radius:12px}.tag{letter-spacing:3px;font-size:12px;color:#c7a872}.chapters{display:grid;grid-template-columns:repeat(3,minmax(0,1fr));gap:10px;margin-top:15px}button{background:#28231a;border:1px solid #4d4231;border-radius:8px;color:#eee5d4;text-align:left;padding:15px;cursor:pointer}button span{display:block;color:#bc9e6b}.shorts{display:grid;grid-template-columns:repeat(3,minmax(0,1fr));gap:24px}.shorts article{min-width:0}.shorts video{aspect-ratio:9/16;max-height:660px}.note{padding:20px;border-left:2px solid #aa8955;background:#242018}li{margin:8px 0}@media(max-width:720px){.chapters,.shorts{grid-template-columns:1fr}.shorts article{min-width:0}.shorts video{max-height:75vh}main{padding:30px 18px}}</style><main><div class="tag">AARON GUO / FIELD NOTES 01</div><h1>The desert has a voice.</h1><p>8 分 57 秒 · 纯英文长片 · 1080p<br>从真实鸣沙录音，到实验室里的声音，再走进粮仓和机器人抓手。保留原有声音风格，加入六个章节音乐引入和叙述下的轻背景音乐。</p><video id="film" controls playsinline preload="metadata" src="film.mp4"></video><div class="chapters">CHAPTERS</div><p><a href="film.mp4" download>下载完整版</a> · <a href="youtube-script.md">完整英文文案</a> · <a href="qa/artifacts.json">成片规格</a></p><h2>同一部长片，三个独立入口</h2><p>按完整语义截取，重新编排竖屏构图、标题和字幕。全部为英文版。</p><div class="shorts">SHORTS</div><h2>这一版增加了什么</h2><p>声音怎样通过空气传播；科学家怎样控制实验条件；音高、响度和单一音调的区别；短促声与持续轰鸣的研究；粮仓中的摩擦与振动；以及真空颗粒抓手。研究仍有不同解释，相关应用与鸣沙之间的关系也做了明确限定。</p><div class="note">真实录音来自 NPS；沙丘照片署名 Kurt Moses / NPS。颗粒、粮仓和抓手图片是 AI 示意图，动画为解释性重绘。新配乐为原创生成音乐；本页用于内部审片，尚未发布。</div><h2>科学与素材来源</h2><ul>REFS</ul></main><script>function seek(t){const v=document.getElementById('film');v.currentTime=t;v.play();v.scrollIntoView({behavior:'smooth',block:'center'})}document.querySelectorAll('video').forEach(v=>v.addEventListener('play',()=>document.querySelectorAll('video').forEach(o=>{if(o!==v)o.pause()})))</script></html>'''
(p/'review.html').write_text(page.replace('CHAPTERS',chapters).replace('SHORTS',shorts).replace('REFS',refs))
old=p.parent/'singing-sands-full-2026-09-08/serve.py';(p/'serve.py').write_text(old.read_text().replace("8770","8772"))
