// Generated by build-data.py — do not edit by hand.
export type Cues = Record<string, number>;
export interface SceneData { id: string; kind: string; start: number; end: number; fade: boolean; header: boolean; captions: boolean; cues: Cues }
export interface FilmData {
  fps: number; audio: string; audioOffset: number; narrationEnd: number; finalHoldEnd: number; filmEnd: number;
  chapters: { at: number; seq: string; label: string }[];
  captions: { start: number; end: number; text: string }[];
  scenes: SceneData[];
}
export const data: FilmData = {
 "fps": 30,
 "audio": "narration-paced-1.10.mp3",
 "audioOffset": 2.2,
 "narrationEnd": 506.273,
 "finalHoldEnd": 507.2,
 "filmEnd": 512.2,
 "chapters": [
  {
   "at": 0.0,
   "seq": "LINE 00",
   "label": "THE METER"
  },
  {
   "at": 26.266,
   "seq": "LINE 01",
   "label": "THE SENTENCE THAT MATTERS"
  },
  {
   "at": 68.196,
   "seq": "LINE 02",
   "label": "TWENTY DOLLARS PER UNIT"
  },
  {
   "at": 109.511,
   "seq": "LINE 03",
   "label": "FIVE WORDS"
  },
  {
   "at": 150.352,
   "seq": "LINE 04",
   "label": "MY THIRTY-DAY BILL"
  },
  {
   "at": 207.827,
   "seq": "LINE 05",
   "label": "THE RE-READ"
  },
  {
   "at": 270.331,
   "seq": "LINE 06",
   "label": "THE PRICE THAT MATTERS"
  },
  {
   "at": 301.99,
   "seq": "LINE 07",
   "label": "MODEL BEATS VENDOR"
  },
  {
   "at": 355.605,
   "seq": "LINE 08",
   "label": "BEFORE OCTOBER 29"
  },
  {
   "at": 385.674,
   "seq": "LINE 09",
   "label": "WHAT COMES NEXT"
  },
  {
   "at": 420.983,
   "seq": "LINE 10",
   "label": "PRICE YOUR OWN BILL"
  },
  {
   "at": 468.422,
   "seq": "LINE 11",
   "label": "A BILL I CAN FINALLY READ"
  }
 ],
 "captions": [
  {
   "start": 2.2,
   "end": 3.867,
   "text": "Five times in September,"
  },
  {
   "start": 4.153,
   "end": 6.992,
   "text": "the weekly meter on my two-hundred-dollar Codex"
  },
  {
   "start": 7.065,
   "end": 9.282,
   "text": "plan hit one hundred percent."
  },
  {
   "start": 9.884,
   "end": 11.615,
   "text": "Then OpenAI emailed me."
  },
  {
   "start": 11.996,
   "end": 14.867,
   "text": "Starting October thirtieth, the same two hundred"
  },
  {
   "start": 14.888,
   "end": 16.683,
   "text": "dollars buys half as much."
  },
  {
   "start": 17.063,
   "end": 19.395,
   "text": "So I opened my logs and priced"
  },
  {
   "start": 19.5,
   "end": 22.255,
   "text": "every token I used in the last thirty days."
  },
  {
   "start": 22.901,
   "end": 26.246,
   "text": "The expensive part wasn't what I expected."
  },
  {
   "start": 26.246,
   "end": 27.355,
   "text": "Here's what changed."
  },
  {
   "start": 27.399,
   "end": 29.689,
   "text": "Pro 200 drops from twenty times the"
  },
  {
   "start": 29.742,
   "end": 31.589,
   "text": "Plus allowance to ten times,"
  },
  {
   "start": 31.864,
   "end": 34.027,
   "text": "in Codex and ChatGPT Work."
  },
  {
   "start": 34.587,
   "end": 35.516,
   "text": "Same price."
  },
  {
   "start": 36.174,
   "end": 38.781,
   "text": "Existing subscribers keep the old limits until"
  },
  {
   "start": 38.834,
   "end": 41.495,
   "text": "October twenty-ninth, plus a one-time grant of"
  },
  {
   "start": 41.579,
   "end": 44.196,
   "text": "credits worth two thousand five hundred dollars"
  },
  {
   "start": 44.481,
   "end": 46.698,
   "text": "that expires at year end."
  },
  {
   "start": 47.206,
   "end": 48.684,
   "text": "But the line I keep coming back"
  },
  {
   "start": 48.736,
   "end": 50.436,
   "text": "to came the night before,"
  },
  {
   "start": 50.594,
   "end": 52.853,
   "text": "from Tibo, who leads Codex."
  },
  {
   "start": 53.235,
   "end": 55.187,
   "text": "He wrote that the new plan \"will"
  },
  {
   "start": 55.251,
   "end": 58.153,
   "text": "net out at half the dollar in API spend.\""
  },
  {
   "start": 58.989,
   "end": 60.931,
   "text": "Half the dollar in API spend."
  },
  {
   "start": 60.531,
   "end": 61.893,
   "text": "That's the unit now."
  },
  {
   "start": 63.056,
   "end": 65.399,
   "text": "Your subscription is a prepaid budget,"
  },
  {
   "start": 65.063,
   "end": 68.176,
   "text": "measured in API dollars."
  },
  {
   "start": 68.177,
   "end": 69.411,
   "text": "Once you see the unit,"
  },
  {
   "start": 69.752,
   "end": 71.367,
   "text": "the price list reads differently."
  },
  {
   "start": 71.991,
   "end": 73.954,
   "text": "Plus is twenty dollars for one unit."
  },
  {
   "start": 74.251,
   "end": 76.573,
   "text": "Pro 100 is five units for a hundred."
  },
  {
   "start": 76.86,
   "end": 78.781,
   "text": "The new Pro 200 is ten units"
  },
  {
   "start": 78.833,
   "end": 79.667,
   "text": "for two hundred."
  },
  {
   "start": 80.133,
   "end": 83.036,
   "text": "Pro 500 is twenty-five units for five hundred."
  },
  {
   "start": 83.354,
   "end": 85.761,
   "text": "Every tier is twenty dollars per unit."
  },
  {
   "start": 86.153,
   "end": 88.761,
   "text": "The old Pro 200 was the only exception."
  },
  {
   "start": 89.131,
   "end": 91.19,
   "text": "Twenty units for two hundred dollars."
  },
  {
   "start": 91.498,
   "end": 92.764,
   "text": "Ten dollars a unit."
  },
  {
   "start": 93.516,
   "end": 95.204,
   "text": "That was the bulk discount,"
  },
  {
   "start": 95.531,
   "end": 97.294,
   "text": "and it's the thing that's going away."
  },
  {
   "start": 97.676,
   "end": 99.755,
   "text": "Pro 500 doesn't bring it back."
  },
  {
   "start": 99.967,
   "end": 102.753,
   "text": "It sells a higher ceiling, and speed."
  },
  {
   "start": 103.136,
   "end": 106.081,
   "text": "A flat rate, with a premium for performance."
  },
  {
   "start": 106.462,
   "end": 109.491,
   "text": "That's how cloud providers price."
  },
  {
   "start": 109.491,
   "end": 112.024,
   "text": "A lot of the reaction was about delivery."
  },
  {
   "start": 112.364,
   "end": 114.421,
   "text": "The cut went out about ten hours"
  },
  {
   "start": 114.505,
   "end": 116.902,
   "text": "before OpenAI's DevDay keynote."
  },
  {
   "start": 117.377,
   "end": 119.668,
   "text": "On Hacker News, the reply I kept"
  },
  {
   "start": 119.774,
   "end": 122.56,
   "text": "seeing was: \"Simply say 'we're cutting limits"
  },
  {
   "start": 122.624,
   "end": 124.386,
   "text": "in half.' Five words.\""
  },
  {
   "start": 124.779,
   "end": 126.743,
   "text": "Several people said they'd already moved to"
  },
  {
   "start": 126.816,
   "end": 128.453,
   "text": "Claude Opus 5.5."
  },
  {
   "start": 128.624,
   "end": 130.945,
   "text": "The most-engaged post took the other side:"
  },
  {
   "start": 131.401,
   "end": 133.565,
   "text": "the old plan was worth about fourteen"
  },
  {
   "start": 133.596,
   "end": 135.623,
   "text": "thousand a month in API value,"
  },
  {
   "start": 135.886,
   "end": 136.985,
   "text": "the new one seven,"
  },
  {
   "start": 137.29,
   "end": 138.652,
   "text": "Claude Max about eight."
  },
  {
   "start": 139.129,
   "end": 140.259,
   "text": "Barely a difference."
  },
  {
   "start": 140.617,
   "end": 141.99,
   "text": "I can't verify that."
  },
  {
   "start": 142.265,
   "end": 144.556,
   "text": "But notice both sides are now arguing"
  },
  {
   "start": 144.63,
   "end": 145.907,
   "text": "in API dollars."
  },
  {
   "start": 146.479,
   "end": 150.332,
   "text": "So I stopped reading estimates and pulled my own."
  },
  {
   "start": 150.331,
   "end": 151.936,
   "text": "I pay two hundred a month for"
  },
  {
   "start": 151.998,
   "end": 155.398,
   "text": "ChatGPT Pro, and two hundred for Claude Max."
  },
  {
   "start": 155.632,
   "end": 157.036,
   "text": "I use both every day,"
  },
  {
   "start": 157.27,
   "end": 159.117,
   "text": "usually with several agents running."
  },
  {
   "start": 159.868,
   "end": 162.031,
   "text": "Both tools keep session logs on disk,"
  },
  {
   "start": 162.108,
   "end": 164.007,
   "text": "with token counts for every turn."
  },
  {
   "start": 164.684,
   "end": 166.298,
   "text": "I took thirty days from my main"
  },
  {
   "start": 166.362,
   "end": 169.813,
   "text": "machine and priced every token at API list price."
  },
  {
   "start": 169.983,
   "end": 173.437,
   "text": "Claude Code: about nine thousand four hundred dollars."
  },
  {
   "start": 173.892,
   "end": 175.634,
   "text": "Codex, on my Pro account:"
  },
  {
   "start": 175.781,
   "end": 177.47,
   "text": "about three thousand six hundred."
  },
  {
   "start": 177.863,
   "end": 180.153,
   "text": "And Codex is the one that hit the wall."
  },
  {
   "start": 180.417,
   "end": 182.211,
   "text": "Five of six weekly windows,"
  },
  {
   "start": 182.358,
   "end": 184.649,
   "text": "at ninety-nine or one hundred percent."
  },
  {
   "start": 185.094,
   "end": 185.97,
   "text": "Two caveats."
  },
  {
   "start": 186.352,
   "end": 187.693,
   "text": "This is what the work would have"
  },
  {
   "start": 187.756,
   "end": 189.107,
   "text": "cost on the API,"
  },
  {
   "start": 189.276,
   "end": 190.331,
   "text": "not what I paid."
  },
  {
   "start": 190.545,
   "end": 191.589,
   "text": "And it's one machine,"
  },
  {
   "start": 191.685,
   "end": 193.078,
   "text": "so Codex is a floor."
  },
  {
   "start": 193.375,
   "end": 194.968,
   "text": "One heavy user's receipt,"
  },
  {
   "start": 195.243,
   "end": 196.33,
   "text": "not a benchmark."
  },
  {
   "start": 196.626,
   "end": 199.254,
   "text": "Still, both plans are heavily subsidized."
  },
  {
   "start": 199.625,
   "end": 202.58,
   "text": "The question is which meter runs out first."
  },
  {
   "start": 203.026,
   "end": 204.588,
   "text": "For me it was Codex,"
  },
  {
   "start": 204.809,
   "end": 207.807,
   "text": "and that's the one getting cut in half."
  },
  {
   "start": 207.807,
   "end": 209.316,
   "text": "Now the part that surprised me."
  },
  {
   "start": 210.151,
   "end": 212.051,
   "text": "I split the bill by line item."
  },
  {
   "start": 212.191,
   "end": 215.178,
   "text": "I expected output tokens to be the big cost."
  },
  {
   "start": 215.536,
   "end": 218.756,
   "text": "On Astra, output is fifty dollars per million."
  },
  {
   "start": 219.243,
   "end": 220.594,
   "text": "It was a small slice."
  },
  {
   "start": 220.86,
   "end": 222.633,
   "text": "The big number was cache reads."
  },
  {
   "start": 223.002,
   "end": 225.271,
   "text": "Seventy-eight percent of my Astra cost."
  },
  {
   "start": 225.453,
   "end": 227.606,
   "text": "Seventy-six percent of Opus 5."
  },
  {
   "start": 227.999,
   "end": 230.373,
   "text": "Fifty-eight percent of Opus 5.5."
  },
  {
   "start": 230.721,
   "end": 231.481,
   "text": "Here's why."
  },
  {
   "start": 231.937,
   "end": 233.51,
   "text": "An agent doesn't answer once."
  },
  {
   "start": 233.817,
   "end": 234.661,
   "text": "It runs a loop."
  },
  {
   "start": 235.043,
   "end": 236.331,
   "text": "Load the repo context,"
  },
  {
   "start": 236.638,
   "end": 238.473,
   "text": "call a tool, read the result,"
  },
  {
   "start": 238.601,
   "end": 239.73,
   "text": "think, go again."
  },
  {
   "start": 240.036,
   "end": 243.107,
   "text": "And every turn, it re-reads the conversation so far."
  },
  {
   "start": 243.468,
   "end": 246.867,
   "text": "Caching makes each re-read cheaper than fresh input."
  },
  {
   "start": 247.343,
   "end": 249.064,
   "text": "But the volume is enormous."
  },
  {
   "start": 249.299,
   "end": 251.853,
   "text": "In thirty days, my Claude Code sessions"
  },
  {
   "start": 251.959,
   "end": 255.02,
   "text": "read about seventeen billion tokens from cache."
  },
  {
   "start": 256.003,
   "end": 257.915,
   "text": "Three weeks ago I praised Astra for"
  },
  {
   "start": 257.979,
   "end": 261.092,
   "text": "carrying a whole deployment without handing it back."
  },
  {
   "start": 262.255,
   "end": 264.81,
   "text": "Carrying the whole job means re-reading it,"
  },
  {
   "start": 265.0,
   "end": 266.161,
   "text": "hundreds of times."
  },
  {
   "start": 266.1,
   "end": 268.379,
   "text": "The capability I praised is exactly what"
  },
  {
   "start": 268.421,
   "end": 270.311,
   "text": "the bill is made of."
  },
  {
   "start": 270.311,
   "end": 271.25,
   "text": "So for agent work,"
  },
  {
   "start": 271.282,
   "end": 272.918,
   "text": "the price that matters isn't the big"
  },
  {
   "start": 272.992,
   "end": 275.398,
   "text": "input and output numbers on the pricing page."
  },
  {
   "start": 275.599,
   "end": 277.182,
   "text": "It's the cache-read price."
  },
  {
   "start": 277.753,
   "end": 280.666,
   "text": "GPT-6 Astra: one dollar per million."
  },
  {
   "start": 280.941,
   "end": 283.221,
   "text": "Claude Opus 5: fifty cents."
  },
  {
   "start": 283.495,
   "end": 285.86,
   "text": "Fable 5.1: twenty-five cents."
  },
  {
   "start": 286.071,
   "end": 288.192,
   "text": "Opus 5.5: twenty cents."
  },
  {
   "start": 288.046,
   "end": 290.462,
   "text": "GPT-6.1 Sol: ten cents."
  },
  {
   "start": 290.758,
   "end": 293.418,
   "text": "This is where September's price cuts actually landed."
  },
  {
   "start": 293.789,
   "end": 295.541,
   "text": "On the line item agents burn."
  },
  {
   "start": 296.07,
   "end": 298.233,
   "text": "On a workload that's three-quarters re-reading,"
  },
  {
   "start": 298.36,
   "end": 301.97,
   "text": "Astra costs five times what Opus 5.5 costs."
  },
  {
   "start": 301.969,
   "end": 304.302,
   "text": "So which plan is the better deal?"
  },
  {
   "start": 304.588,
   "end": 305.877,
   "text": "For my September workload,"
  },
  {
   "start": 305.94,
   "end": 309.085,
   "text": "Claude Max, and by more than I expected."
  },
  {
   "start": 309.731,
   "end": 311.008,
   "text": "Same two hundred dollars."
  },
  {
   "start": 311.388,
   "end": 313.457,
   "text": "About nine thousand four hundred of work"
  },
  {
   "start": 313.531,
   "end": 314.386,
   "text": "on one side."
  },
  {
   "start": 314.588,
   "end": 316.551,
   "text": "About three thousand six hundred on the"
  },
  {
   "start": 316.625,
   "end": 319.127,
   "text": "other, before the meter capped out."
  },
  {
   "start": 319.518,
   "end": 321.629,
   "text": "But here's the bigger lever in my logs."
  },
  {
   "start": 321.883,
   "end": 323.012,
   "text": "It wasn't the vendor."
  },
  {
   "start": 323.202,
   "end": 324.184,
   "text": "It was the model."
  },
  {
   "start": 324.639,
   "end": 326.498,
   "text": "Take the exact tokens I ran on"
  },
  {
   "start": 326.603,
   "end": 330.413,
   "text": "Astra and price them at GPT-6.1 Sol."
  },
  {
   "start": 330.901,
   "end": 334.711,
   "text": "About twenty-nine hundred dollars becomes about three hundred fifty."
  },
  {
   "start": 334.933,
   "end": 335.925,
   "text": "Twelve percent."
  },
  {
   "start": 336.348,
   "end": 338.691,
   "text": "Inside Claude, my Opus 5 tokens,"
  },
  {
   "start": 338.881,
   "end": 340.929,
   "text": "repriced at Opus 5.5,"
  },
  {
   "start": 341.129,
   "end": 342.407,
   "text": "drop by about half."
  },
  {
   "start": 342.503,
   "end": 344.604,
   "text": "That's OpenAI's bet with this plan."
  },
  {
   "start": 344.952,
   "end": 346.683,
   "text": "Move the work to the cheaper model,"
  },
  {
   "start": 346.989,
   "end": 349.649,
   "text": "and the halved allowance covers the same work."
  },
  {
   "start": 350.422,
   "end": 352.808,
   "text": "Can Sol do the work I've been giving Astra?"
  },
  {
   "start": 352.872,
   "end": 353.79,
   "text": "I don't know yet."
  },
  {
   "start": 353.98,
   "end": 355.585,
   "text": "I haven't tested it."
  },
  {
   "start": 355.584,
   "end": 357.379,
   "text": "So here's what I'm actually doing."
  },
  {
   "start": 357.845,
   "end": 358.246,
   "text": "One."
  },
  {
   "start": 358.534,
   "end": 360.698,
   "text": "Claude Max stays my main tool."
  },
  {
   "start": 361.173,
   "end": 361.617,
   "text": "Two."
  },
  {
   "start": 361.999,
   "end": 364.817,
   "text": "I keep Pro 200 through December thirty-first,"
  },
  {
   "start": 365.071,
   "end": 367.319,
   "text": "to use those credits before they expire."
  },
  {
   "start": 367.606,
   "end": 369.137,
   "text": "I'm not buying Pro 500."
  },
  {
   "start": 369.455,
   "end": 371.682,
   "text": "Same unit price, three hundred more a"
  },
  {
   "start": 371.777,
   "end": 373.487,
   "text": "month, mostly for speed."
  },
  {
   "start": 374.502,
   "end": 374.967,
   "text": "Three."
  },
  {
   "start": 374.673,
   "end": 376.763,
   "text": "In October, I run Codex on"
  },
  {
   "start": 376.837,
   "end": 379.644,
   "text": "GPT-6.1 Sol for a week and"
  },
  {
   "start": 379.75,
   "end": 380.774,
   "text": "watch the meter."
  },
  {
   "start": 381.821,
   "end": 383.995,
   "text": "If Sol carries most of the work,"
  },
  {
   "start": 383.712,
   "end": 385.654,
   "text": "ten times might be enough."
  },
  {
   "start": 385.654,
   "end": 386.878,
   "text": "Now, my guesses."
  },
  {
   "start": 387.492,
   "end": 388.864,
   "text": "These are my inferences,"
  },
  {
   "start": 388.907,
   "end": 390.901,
   "text": "not anything either company has said."
  },
  {
   "start": 391.527,
   "end": 394.238,
   "text": "First, the \"twenty x\" language fades and"
  },
  {
   "start": 394.281,
   "end": 396.065,
   "text": "the dollar budget becomes visible."
  },
  {
   "start": 396.319,
   "end": 398.357,
   "text": "OpenAI has already done the conversion."
  },
  {
   "start": 398.728,
   "end": 401.958,
   "text": "Second, the price war moves to what agents consume."
  },
  {
   "start": 402.234,
   "end": 403.458,
   "text": "Cheaper cache reads."
  },
  {
   "start": 403.733,
   "end": 405.02,
   "text": "A premium for speed."
  },
  {
   "start": 405.413,
   "end": 408.147,
   "text": "Third, heavy-user subsidies keep shrinking."
  },
  {
   "start": 408.36,
   "end": 410.534,
   "text": "A company that publishes the exchange rate"
  },
  {
   "start": 410.587,
   "end": 412.698,
   "text": "has built the dial it'll turn next"
  },
  {
   "start": 412.729,
   "end": 414.292,
   "text": "time capacity gets tight."
  },
  {
   "start": 414.842,
   "end": 416.858,
   "text": "Plan as if your subscription is a"
  },
  {
   "start": 416.921,
   "end": 420.963,
   "text": "prepaid API budget, not an unlimited pass."
  },
  {
   "start": 420.963,
   "end": 422.504,
   "text": "If you want to do this yourself,"
  },
  {
   "start": 422.642,
   "end": 423.739,
   "text": "it's four steps."
  },
  {
   "start": 423.889,
   "end": 424.923,
   "text": "Find the logs."
  },
  {
   "start": 425.208,
   "end": 427.636,
   "text": "Codex keeps session files under a sessions"
  },
  {
   "start": 427.72,
   "end": 429.915,
   "text": "folder in its home directory."
  },
  {
   "start": 430.677,
   "end": 433.104,
   "text": "Claude Code keeps them under projects in"
  },
  {
   "start": 433.147,
   "end": 434.212,
   "text": "its home directory."
  },
  {
   "start": 434.551,
   "end": 436.176,
   "text": "Both record tokens per turn."
  },
  {
   "start": 436.461,
   "end": 437.992,
   "text": "Pull four numbers per model."
  },
  {
   "start": 438.276,
   "end": 440.133,
   "text": "Fresh input, cache writes,"
  },
  {
   "start": 440.282,
   "end": 441.981,
   "text": "cache reads, and output."
  },
  {
   "start": 441.992,
   "end": 444.695,
   "text": "Multiply each by that model's list price."
  },
  {
   "start": 444.98,
   "end": 446.563,
   "text": "Then find your biggest line."
  },
  {
   "start": 447.103,
   "end": 448.972,
   "text": "For me, it was the re-read."
  },
  {
   "start": 449.269,
   "end": 450.335,
   "text": "Then three habits."
  },
  {
   "start": 450.621,
   "end": 452.404,
   "text": "Route by task, not loyalty."
  },
  {
   "start": 452.66,
   "end": 454.359,
   "text": "Treat context as a cost,"
  },
  {
   "start": 454.612,
   "end": 457.422,
   "text": "because long sessions dragging stale files"
  },
  {
   "start": 457.495,
   "end": 459.754,
   "text": "through hundreds of turns are the bill."
  },
  {
   "start": 460.284,
   "end": 461.466,
   "text": "And stay portable."
  },
  {
   "start": 462.302,
   "end": 464.687,
   "text": "My workflows run in both tools,"
  },
  {
   "start": 464.909,
   "end": 466.755,
   "text": "so switching is a pricing decision,"
  },
  {
   "start": 467.009,
   "end": 468.402,
   "text": "not a migration."
  },
  {
   "start": 468.402,
   "end": 470.671,
   "text": "That meter hit one hundred percent five"
  },
  {
   "start": 470.703,
   "end": 473.015,
   "text": "times last month, and I never asked"
  },
  {
   "start": 473.088,
   "end": 475.104,
   "text": "what one hundred percent was worth."
  },
  {
   "start": 475.222,
   "end": 476.678,
   "text": "Now I know the unit,"
  },
  {
   "start": 476.868,
   "end": 478.125,
   "text": "and I've read the bill."
  },
  {
   "start": 478.633,
   "end": 480.279,
   "text": "I'm not angry about the change."
  },
  {
   "start": 480.429,
   "end": 481.843,
   "text": "The timing was clumsy,"
  },
  {
   "start": 481.875,
   "end": 484.819,
   "text": "and \"we're changing how we calculate usage\""
  },
  {
   "start": 485.009,
   "end": 487.3,
   "text": "was a worse sentence than \"we're cutting"
  },
  {
   "start": 487.406,
   "end": 488.503,
   "text": "it in half.\""
  },
  {
   "start": 488.885,
   "end": 491.259,
   "text": "But a subscription with a published exchange"
  },
  {
   "start": 491.312,
   "end": 494.384,
   "text": "rate is more honest than a magic multiple."
  }
 ],
 "scenes": [
  {
   "id": "s01-cold-open-3d",
   "kind": "coldopen3d",
   "start": 0.0,
   "end": 26.266,
   "fade": false,
   "header": false,
   "captions": true,
   "cues": {
    "drift": 0.1,
    "lead": 2.2,
    "meter": 2.8,
    "hit": 7.815,
    "email": 9.884,
    "half": 15.722,
    "logs": 17.063,
    "priced": 19.046,
    "expensive": 22.901,
    "expected": 24.04
   }
  },
  {
   "id": "s04-plan-terms",
   "kind": "terms",
   "start": 26.266,
   "end": 46.906,
   "fade": true,
   "header": true,
   "captions": true,
   "cues": {
    "r1": 27.399,
    "r1b": 30.596,
    "r2": 34.587,
    "r3": 36.174,
    "r4": 40.176
   }
  },
  {
   "id": "s05-tibo-quote",
   "kind": "tibo",
   "start": 46.906,
   "end": 60.951,
   "fade": true,
   "header": true,
   "captions": true,
   "cues": {
    "attr": 50.594,
    "quote": 54.903,
    "echo": 56.021
   }
  },
  {
   "id": "s06-the-unit",
   "kind": "unit",
   "start": 60.951,
   "end": 68.196,
   "fade": true,
   "header": true,
   "captions": true,
   "cues": {
    "sub": 63.056
   }
  },
  {
   "id": "s07-per-unit",
   "kind": "perunit",
   "start": 68.196,
   "end": 97.376,
   "fade": true,
   "header": true,
   "captions": true,
   "cues": {
    "r1": 71.991,
    "r2": 74.251,
    "r3": 76.86,
    "r4": 80.133,
    "col": 83.354,
    "old": 86.153,
    "ten": 91.498,
    "gone": 93.516
   }
  },
  {
   "id": "s08-flat-rate",
   "kind": "flatrate",
   "start": 97.376,
   "end": 109.511,
   "fade": true,
   "header": true,
   "captions": true,
   "cues": {
    "speed": 99.967,
    "flat": 103.136,
    "cloud": 106.462
   }
  },
  {
   "id": "s09-five-words",
   "kind": "fivewords",
   "start": 109.511,
   "end": 128.473,
   "fade": true,
   "header": true,
   "captions": true,
   "cues": {
    "timing": 112.364,
    "quote": 120.523,
    "five": 123.479,
    "moved": 124.779
   }
  },
  {
   "id": "s10-other-side",
   "kind": "otherside",
   "start": 128.473,
   "end": 150.352,
   "fade": true,
   "header": true,
   "captions": true,
   "cues": {
    "r1": 133.143,
    "r2": 135.886,
    "r3": 137.29,
    "barely": 139.129,
    "verify": 140.617,
    "both": 142.265,
    "mine": 146.479
   }
  },
  {
   "id": "s11-my-setup",
   "kind": "setup",
   "start": 150.352,
   "end": 169.833,
   "fade": true,
   "header": true,
   "captions": true,
   "cues": {
    "r1": 150.552,
    "r2": 153.603,
    "r3": 155.632,
    "r4": 159.868,
    "r5": 164.684
   }
  },
  {
   "id": "s12-totals",
   "kind": "totals",
   "start": 169.833,
   "end": 177.563,
   "fade": true,
   "header": true,
   "captions": true,
   "cues": {
    "n1": 169.983,
    "n2": 173.892
   }
  },
  {
   "id": "s13-meter-exhibit",
   "kind": "meter",
   "start": 177.563,
   "end": 184.794,
   "fade": true,
   "header": true,
   "captions": true,
   "cues": {
    "label": 178.063,
    "five": 180.417
   }
  },
  {
   "id": "s14-caveats",
   "kind": "caveats",
   "start": 184.794,
   "end": 196.35,
   "fade": true,
   "header": true,
   "captions": true,
   "cues": {
    "c1": 186.352,
    "c2": 190.545,
    "receipt": 193.375
   }
  },
  {
   "id": "s15-which-meter",
   "kind": "whichmeter",
   "start": 196.35,
   "end": 207.827,
   "fade": true,
   "header": true,
   "captions": true,
   "cues": {
    "q": 199.625,
    "codex": 203.026
   }
  },
  {
   "id": "s16-line-items",
   "kind": "receipt",
   "start": 207.827,
   "end": 220.614,
   "fade": true,
   "header": true,
   "captions": true,
   "cues": {
    "split": 210.151,
    "expect": 212.191,
    "astra": 215.536,
    "small": 219.243
   }
  },
  {
   "id": "s17-the-reveal",
   "kind": "receipt",
   "start": 220.614,
   "end": 230.421,
   "fade": false,
   "header": true,
   "captions": true,
   "cues": {
    "amber": 220.814,
    "astra": 223.002,
    "opus5": 225.453,
    "opus55": 227.999
   }
  },
  {
   "id": "s18-reread-3d",
   "kind": "reread3d",
   "start": 230.421,
   "end": 255.703,
   "fade": true,
   "header": true,
   "captions": true,
   "cues": {
    "loop": 233.817,
    "ctx": 235.043,
    "tool": 236.638,
    "result": 237.619,
    "think": 238.601,
    "again": 239.075,
    "every": 240.036,
    "cache": 243.468,
    "volume": 247.343,
    "thirty": 249.299,
    "num": 252.697
   }
  },
  {
   "id": "s20-astra-callback",
   "kind": "astra",
   "start": 255.703,
   "end": 270.331,
   "fade": true,
   "header": true,
   "captions": true,
   "cues": {
    "label": 256.203,
    "carry": 262.255,
    "praised": 266.1
   }
  },
  {
   "id": "s21-cache-price",
   "kind": "price",
   "start": 270.331,
   "end": 301.99,
   "fade": true,
   "header": true,
   "captions": true,
   "cues": {
    "col": 275.599,
    "r1": 277.753,
    "r2": 280.941,
    "r3": 283.495,
    "r4": 286.071,
    "r5": 288.046,
    "landed": 290.758,
    "five": 296.07
   }
  },
  {
   "id": "s22-verdict",
   "kind": "verdict",
   "start": 301.99,
   "end": 309.431,
   "fade": true,
   "header": true,
   "captions": true,
   "cues": {
    "answer": 304.588,
    "more": 307.354
   }
  },
  {
   "id": "s23-bill-exhibit",
   "kind": "billchart",
   "start": 309.431,
   "end": 319.218,
   "fade": true,
   "header": true,
   "captions": true,
   "cues": {
    "label": 309.931,
    "capped": 317.311
   }
  },
  {
   "id": "s24-the-model",
   "kind": "lever",
   "start": 319.218,
   "end": 324.339,
   "fade": true,
   "header": true,
   "captions": true,
   "cues": {
    "vendor": 321.883,
    "model": 323.202
   }
  },
  {
   "id": "s25-repricing",
   "kind": "repricing",
   "start": 324.339,
   "end": 342.427,
   "fade": true,
   "header": true,
   "captions": true,
   "cues": {
    "label": 324.839,
    "twelve": 334.933,
    "half": 336.348
   }
  },
  {
   "id": "s26-openai-bet",
   "kind": "bet",
   "start": 342.427,
   "end": 355.605,
   "fade": true,
   "header": true,
   "captions": true,
   "cues": {
    "move": 344.952,
    "q": 350.422,
    "untested": 352.872
   }
  },
  {
   "id": "s27-three-moves",
   "kind": "moves",
   "start": 355.605,
   "end": 385.674,
   "fade": true,
   "header": true,
   "captions": true,
   "cues": {
    "m1": 358.534,
    "m2": 361.999,
    "m2b": 367.606,
    "m2c": 369.455,
    "m3": 374.673,
    "m3b": 381.821
   }
  },
  {
   "id": "s28-guesses",
   "kind": "guesses",
   "start": 385.674,
   "end": 414.542,
   "fade": true,
   "header": true,
   "captions": true,
   "cues": {
    "label": 387.492,
    "g1": 391.527,
    "g1b": 396.319,
    "g2": 398.728,
    "g2a": 402.234,
    "g2b": 403.733,
    "g3": 405.413,
    "g3b": 408.36
   }
  },
  {
   "id": "s29-prepaid",
   "kind": "prepaid",
   "start": 414.542,
   "end": 420.983,
   "fade": true,
   "header": true,
   "captions": true,
   "cues": {
    "pass": 418.905
   }
  },
  {
   "id": "s30-price-your-own",
   "kind": "steps",
   "start": 420.983,
   "end": 448.992,
   "fade": true,
   "header": true,
   "captions": true,
   "cues": {
    "s1": 423.889,
    "codex": 425.208,
    "claude": 430.677,
    "s1b": 434.551,
    "s2": 436.461,
    "chips": 438.276,
    "s3": 441.992,
    "s4": 444.98,
    "mine": 447.103
   }
  },
  {
   "id": "s31-habits",
   "kind": "habits",
   "start": 448.992,
   "end": 468.422,
   "fade": true,
   "header": true,
   "captions": true,
   "cues": {
    "h1": 450.621,
    "h2": 452.66,
    "h2b": 454.612,
    "h3": 460.284,
    "h3b": 462.302
   }
  },
  {
   "id": "s32-meter-callback",
   "kind": "metercallback",
   "start": 468.422,
   "end": 475.124,
   "fade": true,
   "header": true,
   "captions": true,
   "cues": {
    "label": 468.922,
    "worth": 472.17
   }
  },
  {
   "id": "s33-read-the-bill",
   "kind": "readbill",
   "start": 475.124,
   "end": 488.585,
   "fade": true,
   "header": true,
   "captions": true,
   "cues": {
    "read": 476.868,
    "angry": 478.633,
    "clumsy": 480.429,
    "worse": 485.009
   }
  },
  {
   "id": "s34-exchange-rate",
   "kind": "exchange",
   "start": 488.585,
   "end": 494.465,
   "fade": true,
   "header": true,
   "captions": true,
   "cues": {
    "honest": 492.125
   }
  },
  {
   "id": "s35-final",
   "kind": "final",
   "start": 494.465,
   "end": 507.2,
   "fade": true,
   "header": false,
   "captions": false,
   "cues": {
    "l1": 494.765,
    "l2": 500.256,
    "l3": 503.751
   }
  },
  {
   "id": "s36-end-card",
   "kind": "end",
   "start": 507.2,
   "end": 512.2,
   "fade": false,
   "header": false,
   "captions": false,
   "cues": {
    "mark": 507.2,
    "line": 507.9
   }
  }
 ]
};
